### ISSUE TITLE
Mismatch between plant_lines and plant_varieties

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#100]
`plant_lines` contains a reference to `plant_varieties` (as `plant_variety_name`); however there are many records where values of this field do not correspond to any known `plant_variety` name:

`SELECT COUNT(*) FROM plant_lines WHERE plant_variety_name NOT IN (SELECT plant_variety_name FROM plant_varieties)`
`COUNT(*): 13271`

I am currently in the process of replacing these string-based PK/FK pairs with standard autoincrementable numerical keys. Under ordinary circumstances this would result in dropping `plant_lines.plant_variety_name`, however - in the interest of preserving data - I intend to leave this field in the table and assign `plant_lines` to `plant_varieties` whenever a match *can* be found (which is ~65% of cases).

@wjurkowski  - please comment if you do not agree with this approach or if you have a better suggestion.

**Comment by sarahcayling** [comment]
This sounds like a good idea -  as we understand it you will simply add an autoincrement key for plant_variety_name in the plant_lines table, which will act as an alias. We are concerned about those lines with a variety_name and no plant_varieties entry! At the meeting we had in March we were given some contact suggestions for people who can help us curate this data. We will follow this up in April.

**Comment by nowakowski** [comment]
@sarahcayling Yes; precisely so. The old FK will be left in the table as a standard text field to enable future curation.

**Comment by nowakowski** [comment]
Fixed by #102

**Comment by teatree1212** [comment]
from a data perspective, has this issue been resolved by curation? As announced by @sarahcayling ?

**Comment by Nuanda** [comment]
According to my knowledge, it is not solved.

**Comment by nowakowski** [comment]
Less than 10% of `PlantLine` records are currently linked to `PlantVariety` records (while approximately 65% of `PlantLine` records in the original CropStore DB had a "matching `PlantVariety` record, the vast majority of these were dummy "unidentified" records which represented missing data).
