### ISSUE TITLE
Main table content for the Traits tab

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#103]
I was wandering if we shouldn't change what is presented when user picks the (current) Traits tab in the data browsing view. When you check http://www.interstoredb.org/Brassica/cs/ you will see this does not really correspond with what people submit using the cs_TRAITS input template (http://cropstoredb.org/input.php).

As I understand it, people are essentially submitting Plant Trials, for specific Plant Populations, that are, in turn, connected with a number of other tables (Plant Scoring Units, Plant Parts, Trait Descriptors and Trait Scores, among others). But the "chief" element is a Plant Trial, right?

The current Interstore data table does not show that, however. Could we, perhaps, change it, and show the list of Plant Trials first, and then allow people to "drill down" into other tables to look for e.g. certain trait scores? This will be in analogy to the Plant Populations table, where people submit PPs and see PPs in the data table.

**Comment by sarahcayling** [comment]
You are right that the trial is the main unit, however it is just an experiment, and therefore it is unlikely that the name will be meaningful to other users - it is more like an experiment ID. Searching for trials by the trait which they tested seems much more useful to users who do not have a specific trial in mind.

**Comment by Nuanda** [comment]
Ok, so we will try to recreate the tables as they are in the CropStore interface. I will try to link trait_scores table from these initial trait_descriptors. I have already added listing plant_trials by project_descriptor (that seemed kind of natural to me).
