### ISSUE TITLE
Unknown plant population names in population_loci

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#105]
There are two `population_loci` with population names which do not exist in `plant_populations`

  - BolNGDH_02 (there exists a `plant_populations` record named `BolNGDH_01`)
  - BraVCS3M_0 (there exists a `plant_populations` record named `BraVCS3M_01`)

Could you suggest what to do with these records?

**Comment by wjurkowski** [comment]
Typos, most likely, as previously: correct and leave the comment to the curator
