### ISSUE TITLE
PP submission do not save PP name properly

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#112]
That was broken by @nowakowski recent PR merge.

@kammerer please fix - not urgent, could be done the next time you work on submissions.

**Comment by kammerer** [comment]
@nowakowski Is there any reason for allowing blank PP#name?

**Comment by nowakowski** [comment]
@kammerer Not to my knowledge - although it's no longer the PK of `plant_populations` so, in principle, blank names shouldn't break anything.
