### ISSUE TITLE
Unknown population name in processed_trait_datasets

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#113]
The `population_id` column in `processed_trait_datasets` has only two distinct values:
  - `BnaTNDH_00` (this is a known population)
  - `BolAGDH_05` (no such population exists, although B. oleracea AGDH populations with lower numbers - up to 04 - are known).

What should we do about the latter record?

**Comment by wjurkowski** [comment]
I'd leave it as it is and mark it for curation

2015-04-03 12:48 GMT+01:00 Piotr Nowakowski <notifications@github.com>:

**Comment by nowakowski** [comment]
Roger that.
