### ISSUE TITLE
Unknown scoring occasion names in trait_scores

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#114]
There are fifteen distinct scoring occasion names in `trait_scores` which do not correspond to any record in `scoring_occasions`:

  - occ_HRI_UN0000_003
  - occ.WHRI_MB0000_002
  - occ.RRES_JB0410_002
  - occ.RRES_JB0310_001
  - occ.WHRI_MB0000_001
  - occ.RRES_JB0410_001
  - occ_PRT7_UN0000_001
  - occ.WHRI_MB0000_003
  - occ_PRT7_UN0000_002
  - occ_HRI_UN0000_001
  - occ.WHRI_MB0000_004
  - occ_HRI_UN0000_002
  - occ_HRI_UN0000_004
  - occ.RRES_JB0310_002
  - occ_PRT7_UN0000_003

I have linked `trait_scores` records to `scoring_occasions` whenever a match can be found (78083 records) and left the FK field null in other cases (31142 records). I have also left the `scoring_occasion_name` field in `trait_scores` to enable future curation. Please tell us if you agree with this approach.

**Comment by wjurkowski** [comment]
Sounds perfect, thumb up!

2015-04-03 13:20 GMT+01:00 Piotr Nowakowski <notifications@github.com>:

**Comment by nowakowski** [comment]
Happy to hear. :)

**Comment by Nuanda** [comment]
See #155 .

**Comment by nowakowski** [comment]
Fixed in #181
