### ISSUE TITLE
Unknown population type for population BraVCS3M_01

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#115]
The population type for population BraVCS3M_01 is undefined. This is the only such record in `plant_populations`. Could you suggest an appropriate `pop_type_lookup` record to attach to this population?

**Comment by wjurkowski** [comment]
There is no 'unspecified' type present in pop_type_lookup
mysql> select distinct population_type from  pop_type_lookup:
+-----------------------------+
| population_type             |
+-----------------------------+
| Azacytidine epi-mutated     |
| Back Cross                  |
| DH segregating              |
| Diversity core collection   |
| Diversity fixed foundation  |
| Diversity foundation        |
| EMS mutated                 |
| Experimental collection     |
| F1 hybrid                   |
| F2                          |
| F3                          |
| F3 pooled                   |
| Gamma irradiated            |
| Genetic resource collection |
| Imortalized F2              |
| Integrated                  |
| Near isogenic               |
| Recombinant inbred          |
| Substitution lines          |
| Variety resource collection |
+-----------------------------+

Maybe we could create such a type? and link it to all empty in
*population_type*

+-----------------------------+
| unspecified                 |
| not applicable              |
| none



2015-04-03 14:04 GMT+01:00 Piotr Nowakowski <notifications@github.com>:

**Comment by nowakowski** [comment]
Indeed, the `unspecified` record was one of those dummy records we ended up removing (these included `unspecified`, `unknown` and `not applicable`. Rather than polluting `pop_type_lookup` with such records I would propose making this relation optional, i.e. enabling NULL values in `plant_populations.population_type`. How about it?

**Comment by wjurkowski** [comment]
OK

2015-04-05 17:28 GMT+01:00 Piotr Nowakowski <notifications@github.com>:

**Comment by Nuanda** [comment]
For the future - should BIP allow users make no assignment to population type or should it require users to choose a population type (as it does now) so all future records have that relation defined?

**Comment by wjurkowski** [comment]
Yes it could be part of QC to require that vital record like that are
completed

2015-04-07 9:32 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by nowakowski** [comment]
Nothing to be done - closing issue.
