### ISSUE TITLE
Oddly named column in genotype_matrices

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#118]
`martix_complied_by` should probably be renamed. While the typo in "martix" is obvious, I am unsure as to the intended meaning of the word "complied". Should we change it to "supplied", "completed" or something else...?

**Comment by wjurkowski** [comment]
I guess it should be matrix_compiled_by
It has one person in it, we will create extra table all_typos_compiled and
send it to Graham  ;)

2015-04-04 12:23 GMT+01:00 Piotr Nowakowski <notifications@github.com>:

**Comment by nowakowski** [comment]
Well, why not? ;)

Seriously, though, thanks for the clarification!

**Comment by nowakowski** [comment]
This has been fixed a while ago.
