### ISSUE TITLE
Cleaning trait scores table

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#123]
Trait scores table is of considerable size (100k+ records) and will probably grow fast. Therefore it would be beneficial to remove useless columns from it. I vote to remove the following:
 - replicate_score_reading: all values equal "1"
 - score_spread: value either empty or "none given"

**Comment by wjurkowski** [comment]
We can imagine that the two might be used in combination to describe where a trait has been scored more than once. However it has never happened, lets clean it up for the time being.

**Comment by Nuanda** [comment]
@nowakowski Piotr, can you take care for this the next time you do some major work with the model? It's not urgent.

**Comment by nowakowski** [comment]
Of course.

**Comment by Nuanda** [comment]
The BIP Saga Part VI: The Return of the Technical Replicate.

@nowakowski Piotr, please add `technical_replicate_number` integer column to TraitScores. Null: false. Set the default and all current TS::technical_replicate_number values to 1.
