### ISSUE TITLE
No Occasion model yet there is occasions table in the schema

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#126]

**Comment by nowakowski** [comment]
See `/app/models/scoring_occasion.rb`. Close the issue if that's what you're looking for.

**Comment by Nuanda** [comment]
No. Of course I know about ScoringOccasion, but that is another table. Perhaps they should be merged or curated in any way, but it has not been done (so far) - there are two tables, two set of records in these tables, yet only a single model.
