### ISSUE TITLE
Deal with select2 stylesheet duplication

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#131]
I was forced to merge #104 but the issue mentioned there by @kammerer still stays. Also, I think we current have this stylesheet duplicated (in both sass and css formats).

**Comment by bchucherko** [comment]
css file was removed in previous commit and scss version was added. Please point me to source code where the file is exclusively added.

**Comment by bchucherko** [comment]
Nevermind, found it.

**Comment by bchucherko** [comment]
fixed
