### ISSUE TITLE
Implicit NULLs in certain model fields

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#133]
Some records appear to "smuggle" blank values in NN (non-nullable) fields - this is evidenced by the presence of `n/a` or `na` string literals.

Suspect models include:

- `qtl.map_qtl_label` (52 records listing `n/a`)
- `design_factors.design_factor_2` (7 records listing `na`)
- `design_factors.design_factor_3` (7 records listing `na`)
- `design_factors.design_factor_4` (2431 records listing `na`)
- `design_factors.design_factor_5` (2431 records listing `na`)

My suggestion would be to drop the NN restriction in the affected fields and convert the above mentioned values to NULL.

**Comment by Nuanda** [comment]
Related to #91

**Comment by nowakowski** [comment]
@wjurkowski Could we request your input here?

**Comment by wjurkowski** [comment]
Could you specify how one or the other scenario (with or without NULLs) can
affect practical work?
I thought having non null fields on default is more efficient?


2015-04-16 11:01 GMT+01:00 Piotr Nowakowski <notifications@github.com>:

**Comment by nowakowski** [comment]
@wjurkowski This would be transparent for end users. Seems to me that if the value of a certain field is missing we should probably not try to conceal this fact by using a default (moreso as the defaults themselves differ - sometimes it's **na**, other times it's **n/a** or even **unspecified** etc.) - this would cause all kinds of headaches for services which perform automatic processing of such data.

Having default values in place of NULLs does not affect the performance of database queries.

**Comment by wjurkowski** [comment]
Agree, it should be transparent! No I got it, let's use nulls instead of
defaults.

2015-04-16 11:33 GMT+01:00 Piotr Nowakowski <notifications@github.com>:
