### ISSUE TITLE
Is 0 a valid value of qtl.qtl_mid_position?

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#134]
Affects 3 records.

**Comment by sarahcayling** [comment]
Hmm... possibly, if the inner_interval_end is zero also, and the qtl_rank is 1. We can't think of other cases, but maybe - one for the long list of data curation tasks...

**Comment by nowakowski** [comment]
@sarahcayling Alas, this is not the case here:
`bip_development=# SELECT id, inner_interval_end, qtl_rank FROM qtl WHERE qtl_mid_position = '0';`
`id  | inner_interval_end  | qtl_rank`
`---+--------------------+----------`
`7    |                     | 1`
`31  |                    | 2`
`96  | 6.6                | 1`

I'll leave it as-is unless you suggest otherwise.

**Comment by Nuanda** [comment]
@wjurkowski confirmed that this may be closed with no further actions.
