### ISSUE TITLE
Setup search action for the front page search bar and present found results

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#140]
For now we may list found plant_populations, plant_lines and plant_varieties. I need information what exactly do you require on the datatables side. I.e. when 7 plant lines are found, and the user clicks on that result, s/he should be able to land on the plant lines data tables view.

I need to know how the filter parameters for that exact set of plant lines are passed to the controller.

**Comment by kammerer** [comment]
I can think of two approaches:
1) passing ids of found records (impractical in case of large result sets)
2) introduce class responsible for search and use it to lookup results as well as provide content for datatables, both search controller and datatables controller would get the same input (plus model for datatables)

**Comment by Nuanda** [comment]
Talking about the 2) option, do you propose to 'persist' the found array of ids in a temporary table, under a unique id, so when the next request comes, the IDs could be extracted and the data could be served?

**Comment by kammerer** [comment]
I thought about simply repeating the search with the same input, however
search results could be easily cached if there is need for that.

2015-04-19 21:48 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Talking about the 2) option, do you propose to 'persist' the found array
> of ids in a temporary table, under a unique id, so when the next request
> comes, the IDs could be extracted and the data could be served?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/140#issuecomment-94308688>
> .
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
All right - I understand that in case of the second query, when we show the resultant datatable to the user, we need to put the query in the context of a single chosen model.
