### ISSUE TITLE
Add link to a chosen PlantVariety when user creates a new PlantLine

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#141]
In the submission step where (and if) the user decides to create a new PL.

**Comment by Nuanda** [comment]
@nowakowski Piotr, we need your input on this: is PL -> PV link *required*? I know you are still in the process of adding validations, but it would help @kammerer to know if he should require user to link a new PL to a PV or not necessary.

**Comment by nowakowski** [comment]
@Nuanda Looking at the data - it should be optional.
