### ISSUE TITLE
Construct 'Additional annotations' button and dialog to be reused in various submission elements

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#154]
Do not show:
 - `entered_by_whom` (just set it directly to the current user email, when finalizing the submission)
 - `date_entered` (just set it directly to the current date, when finalizing the submission)

Use the new dialog in PP submission:
 - in the last step
 - in the new PL form.

**Comment by kammerer** [comment]
If we use dialog in last step of PP submission then this step will have no fields shown by default. Wouldn't you prefer to show everything upfront in this case?

**Comment by Nuanda** [comment]
Yes, I am aware of that. So we may opt to turn the final step into a kind of "confirmation step", where we simply state what is the consequence of finalizing the submission (i.e. the BIP data revocation policy etc.) and, additionally, we allow the user to add some final touches in the form of these annotations.

In such a case, I think, a button with a dialog would be ok (as the screen will not be totally blank anyway).

So, for now I'd go for what's easier to implement - and I guess repeating the dialog solution is simply easier (correct me if I'm wrong). Later on, if we can't provide that additional stuff for the final submission screen, we will may replace it with a plain form.

I also plan to have the same final screen for all of the submissions (with, perhaps, changed information about the consequences of submitting data) - just some info, possibility to add annotations, and to submit the whole thing.
