### ISSUE TITLE
Replace scoring_occasion table with one new column inside the trait_scores table

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#155]
Essentially, the entire scoring_occasion table holds four dates - all else is probably noise (i.e. useful information repeated in other tables, like institute or provenance).

I propose to drop that table and introduce a singe (optional) scoring_date field to trait_scores table, and populate it with score_start/end_date (both are always the same) from the dropped table.

**Comment by wjurkowski** [comment]
Perfect [?]

2015-04-17 13:40 GMT+01:00 Tomasz Gubała <notifications@github.com>:
