### ISSUE TITLE
Test if we can drop PTD.plant_population in favour of PTD.PT.plant_population

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#157]
Please if ProcessedTraitDataset.plant_population is always the same as ProcessedTraitDataset.plant_trial.plant_population and, if so, drop the former.

**Comment by nowakowski** [comment]
Fixed by dropping `processed_trait_dataset.population_id`. Plant population can be reached via ProcessedTraitDataset -> PlantTrial -> PlantPopulation.
