### ISSUE TITLE
Gramene Taxonomy for Plant Line genus - species - subtaxa definition

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#16]
(related to #12)

I have parsed current GR_tax into the system and tried to check which PlantLines could be defined with it. Here is the matching table for species:

present in GR_tax: ["", "alboglabra", "balearica", "barrelieri", "bivoniana", "carinata", "cretica", "deflexa", "drepanensis", "elongata", "fruticulosa", "gravinae", "hilarionis", "incana", "insularis", "juncea", "macrocarpa", "maurorum", "montana", "napus", "nigra", "oleracea", "oxyrrhina", "perviridis", "procumbens", "rapa", "repanda", "rupestris", "souliei", "spinescens", "tournefortii", "villosa"]

absent in GR_tax: ["unspecified", "not applicable", "none", "atlantica", "bourgaei", "oleracia", "bourgeaui", "desnottesii", "nivalis", "juncea?", "rapa and napus", "rapa?", "nigra?", "napus?", "hybrid", "MIXED"]

Issues:
 - "bourgeaui", "oleracia" - simple typos?
 - "rapa and napus", "hybrid", "MIXED" - leave as no species defined?
 - "juncea?", "rapa?", "nigra?", "napus?" - GR_tax do not accommodate for questionable classification: should we assign it anyway but model questionable assignment with a boolean field?
 - "atlantica", "bourgaei", "desnottesii", "nivalis" - four species that are simply not present in GR_tax - file  an addition to Gramene?

Anyway, species is relatively easy :). Going to subtaxa we have bigger problems.

present in GR_tax: ["", "abyssinica", "acephala", "alboglabra", "amplexicaulis", "bivoniana", "botrytis", "capitata", "carinata", "chinensis", "costata", "cretica", "drepanensis", "elongata", "fruticulosa", "gemmifera", "gongylodes", "incana", "insularis", "italica", "juncea", "macrocarpa", "napobrassica", "napus", "narinosa", "nigra", "nipposinica", "oleifera", "oleracea", "parachinensis", "pekinensis", "perviridis", "rapa", "spinescens", "villosa"]

absent in GR_tax: ["Broccoletto Gp", "Neep Greens Gp", "Pak Choi Group", "acephala  viridis", "acephala medullosa", "acephala palmifolia", "acephala ramosa", "acephala sabellica", "acephala viridis", "acephala?", "aegaea", "africana", "alboglabra?", "almeriensis", "biennis", "blancoana", "botrytis botrytis", "botrytis italica", "brachyloma", "cadevallii", "cantabrica", "capitata  rubra", "capitata  sabauda", "capitata alba", "capitata alba conica", "capitata rubra", "capitata sabauda", "capitata?", "captitata", "captitata rubra", "cereptana", "cernua", "chinensis communis", "chinensis parachinensis", "chinensis purpuraria", "chinensis rosularis", "confusa", "crispifolia", "dichotoma", "dimorpha", "dissecta", "djafarensis", "djurdjurae", "folisa", "fruticolosa", "gemnifera", "glaberrima", "glaucescens", "hispida", "integlifolia", "integrifolia", "integrifolia crispifolia", "integrifolia integrifolia", "integrifolia rugosa", "japonica", "laconica", "laevigata", "leptocarpa", "mangolica", "maritima", "melanosperma", "mongolica", "napiformes", "napiformis", "napus annua", "napus biennis", "napus pabularia", "none", "not applicable", "nudicaulis", "oleifera annua", "oleifera biennis", "oleifera sylvestris", "olifeira", "orientales", "pabularia", "pekinensis glabra", "pekinensis laxa", "pekinensis pandurata", "pomeliana", "pseudocampestris", "purpurea", "radicata", "rapa?", "rigida", "ruvo", "sabauda", "sabellica", "sabularia", "sareptana", "suberispifolia", "subintegrifolia", "subsareptana", "subscaposa", "sylvestris", "tinei", "trilocularis", "tronchuda", "tronchuda ?", "tsatsai", "unspecified"]

And I did it the "naive" way - looking for var./subsp. in any species, while there might be same-named var. in different species, right?

Anyway, the real question is as follows: is Gramene Taxonomy useful in anyway? Perhaps it's so outdated it's not worth using it (and imposing it on future BIP users) at all?

**Comment by Nuanda** [comment]
Regarding genus, we have 11 PlantLines with 'X_Brassicoraphanus' genus (no species, no subtaxa).

**Comment by wjurkowski** [comment]
I think its a useful exercise. For the first part this are either typos or
information's missing. Generally, could we find out a way to mark
incomplete/ambiguous records for manual curation? How such a curation could
be enhanced to easy navigate through records and fields?

For the second part its more complicated as we are talking about group of
cultivars within one variety. This particular ontology stays at this level.

   - [i] Brassica oleracea var. acephala (GR_tax:078999)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:078999> #*0*
   - [i] Brassica oleracea var. alboglabra (GR_tax:079000)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079000> #*0*
   - [i] Brassica oleracea var. botrytis (GR_tax:079001)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079001> #*0*
   - [i] Brassica oleracea var. capitata (GR_tax:079002)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079002> #*0*
   - [i] Brassica oleracea var. costata (GR_tax:079003)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079003> #*0*
   - [i] Brassica oleracea var. gemmifera (GR_tax:079004)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079004> #*0*
   - [i] Brassica oleracea var. gongylodes (GR_tax:079005)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079005> #*0*
   - [i] Brassica oleracea var. italica (GR_tax:079006)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079006> #*0*
   - [i] Brassica oleracea var. medullosa (GR_tax:079007)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079007> #*0*
   - [i] Brassica oleracea var. oleracea (GR_tax:079008)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079008> #*0*
   - [i] Brassica oleracea var. ramosa (GR_tax:079009)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079009> #*0*
   - [i] Brassica oleracea var. viridis (GR_tax:079010)
      <http://archive.gramene.org/db/ontology/search?id=GR_tax:079010> #*0*


Therefore using there is no point to resolve more in-depth classifications
hence if we have capitata sabauda, capitala whatevera, capitala tumiwisi we
treat it the same as capitala.
I'm not sure if there is any better taxonomy. We'll look around. Could we
have multiple? just in case they will be complementary?

Regards

2015-02-25 13:56 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Using multiple taxonomies is technically possible - the question is: does that not defeat the idea of taxonomy itself (i.e. to have it standardized)? But sure, we may have more of them and let the user choose.

Anyway, there are two important questions:
 - should we _drop_ the subtaxa part after subspecies/varieties?
 - if we are to impose GR_tax on users when they submit their plant populations, wouldn't that be too constraining to them?

**Comment by wjurkowski** [comment]
yes sure, but we are already beyond taxonomy: species and subspecies is
usually the limit. We go one level deeper to variety and then we have
different cultivars e.g. (decorative kale,[4]
<http://en.wikipedia.org/wiki/Acephala_group#cite_note-4> ornamental kale,
[5] <http://en.wikipedia.org/wiki/Acephala_group#cite_note-5> flowering
kale,[6] <http://en.wikipedia.org/wiki/Acephala_group#cite_note-6> flowering
cabbage,[7] <http://en.wikipedia.org/wiki/Acephala_group#cite_note-7> or
ornamental cabbage)...

2015-02-25 16:27 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by wjurkowski** [comment]
what we need is perhaps cultivar ontology...

2015-02-25 16:46 GMT+00:00 Wiktor Jurkowski <wiktor.jurkowski@gmail.com>:

**Comment by Nuanda** [comment]
All right, let's leave sub-variety levels for now. We have some other problems - mainly: what to do with species and varieties that are not inside GR_tax?

**Comment by wjurkowski** [comment]
Mark for manual curation. There will be two cases: either its missing or
misspelled like "oleracia"

Perhaps we could standardise way to describe missing information (currently
we have trillion different words and spellings). Lets say "NA" and then
move the old value to other field with value to check up by curator?



2015-02-25 16:52 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
All right, I guess we may add a special column to denote a PlantLine record for later curation. Then, after we transfer the data, you may pick those with a simple query in the DB and change values.

Of course, this implies we have _both_ PlatLine relation to GR_tax _and_ genus,species,subtaxa columns.

**Comment by Nuanda** [comment]
@nowakowski Piotr, what do you think? Are you able to give the PlantLine table another column to denote we had problems with assigning a GR taxonomy term to that PL so, later on, someone in TGAC is able to look into the DB and fix those values?

**Comment by Nuanda** [comment]
@wjurkowski Is X_Brassicoraphanus http://archive.gramene.org/db/ontology/search?id=GR_tax:079035 ?

**Comment by nowakowski** [comment]
@Nuanda Well, we don't actually need a separate column. I have written a script which attempts to match a taxonomy record to each `PlantLine` object. The script is very conservative and gives up at the slighest hint of trouble. It is currently able to assign proper taxonomy records to approx. 55% plant lines (14304 of 25694 to be exact). The remaining records are left unassigned so if a `plant_line` has no assigned `taxonomy_term` (i.e. the FK value is NULL) it is in need of curation.

OTOH a dedicated column may help with future housekeeping tasks - so I'm sort of on the fence here. If you think it's a good idea then I'll extend the model.

**Comment by Nuanda** [comment]
Piotr, actually I like what you propose better. The current CropStore model suffers _a lot_ due to data redundancy, let's now follow that way :). Your idea is clear.

The other thing is the sub-varieties level. We will not find that in Gramene. What do you think about adding a fourth column, separating current subtaxa into subsp./var. level and that cultivar sublevel, assigning a PlantLine to GR_tax term on "varietas" level, where we can find it, and leaving the cultivar sublevel as it is (wherever it is assigned, of course)?

**Comment by nowakowski** [comment]
@Nuanda I'm okay with that - but I think this is something @wjurkowski should comment on.

**Comment by wjurkowski** [comment]
sounds good!

2015-02-25 19:14 GMT+00:00 Piotr Nowakowski <notifications@github.com>:

**Comment by nowakowski** [comment]
Since we'll likely be extending the Gramene taxonomy with additional terms, I added a boolean column (`canonical`) to `taxonomy_terms` to indicate which terms were imported from OBO and which ones were added by us. The aforementioned script is now available as a rake task - run `rake curate:plant_taxonomy` to perform the assignment. The script is idempotent (you can run it multiple times as needed).

**Comment by Nuanda** [comment]
Ok, the mapping is partially made in the newest master branch. This is what we did:
 - introduced new taxonomy_terms table where we have loaded all Gramene taxonomy ontology
 - mapped most of plant_lines to that table, leaving not matched varieties as they are, for now.

Piotr is on leave for a couple of days but when he comes back, he plan to:
 - add all non-Gramene varieties and cultivars to taxonomy_terms table, but simply without assigning them any GR_tax id (as there is none)
 - map the rest of plant_lines to that table
 - remove the genus,species,subtaxa trio from plant_lines table altogether.

**Comment by Nuanda** [comment]
I have uploaded the current taxonomy terms list BIP uses internally:

https://github.com/eSpectrum-IT/brassica/blob/master/db/data/taxonomy_terms-28.02.txt

[C] stands for Gramene tax term, [-] for one from CropStore original data. In some cases I tried to validate it against http://www.ars-grin.gov/cgi-bin/npgs/html/taxgenform.pl?language=en but only selectively. @wjurkowski please take a look and tell me if there is something wrong with this list.

Also, this is the rest of plant_lines that we could not match:
  - Brassica oleracea captitata, Brassica oleracea captitata rubra
    - should be 'capitata'?
  - Brassica oleracia
    - should be 'oleracea'?
  - Brassica napus olifeira, Brassica rapa olifeira
    - should be 'oleifera'?
  - Brassica bourgaei unspecified
    - should be 'bourgeaui'?
  - Brassica juncea napiformes
    - should be 'napiformis'?
  - Brassica oleracea capitata alba conica
    - since there is 'Brassica oleracea var. capitata alba' cultivar defined, I guess this is yet another sub-level?
  - Brassica hybrid, Brassica MIXED
    - should we map them to 'Brassica sp.'?
  - Brassica rapa napobrassica, X_Brassicoraphanus, Brassica rapa and napus
    - please tell us how to map these three.

When solved, this will be a step towards database re-normalization. And, of course, to make data meaningful again :).

**Comment by sarahcayling** [comment]
I contacted someone at the CGN genebank, where most of the plant line
records were imported from  to ask if there was a better authority than
Gramene, I've not had a response yet...

**Comment by Nuanda** [comment]
Ok, I guess most of the above is safe to do. Two final questions:
 - shouldn't "Brassica rapa napobrassica" be "Brassica napus var. napobrassica" (the later is defined by Gramene)?
 - should I change "Brassica rapa and napus" into "Brassica rapa x Brassica napus"?

**Comment by wjurkowski** [comment]
Both of them seem to be mistakes and to me your changes are correct. I
think the way to do is following:

This is not a rocket science - we are in most cases able to identify the
correct answer ourselves. Let's do it in this and similar cases.
On the other hand we are not plant authority therefore perhaps:  1) we
could have special field to mark if the record should be verified by
curator; 2) old values could be left in a "comment/free text field"; 3)
this fields would be later removed when curator approves it.

Such an approach will allow quick progress with cleansing at the same time
lowering the risk of loosing any information



2015-03-15 8:54 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Yes, we have a "not canonical" boolean field denoting that in the DB, so you can find terms not originating from Gramene tax later on easily inside the tables.
