### ISSUE TITLE
Optimize postgresql settings on TGAC server

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#169]

**Comment by nowakowski** [comment]
Done. You may also want to tweak your development versions of pgsql by editing the config file (try `/var/lib/pgsql/9.4/data/postgresql.conf` or similar) and having a look at the following settings:

`shared_buffers`: Data cache memory size. Reasonable setting is 1/4 of your system memory.
`effective_cache_size`: Specifies how much memory PGSQL expects to have available once the OS and all other applications have taken their cut. This is NOT an allocation but merely a guideline used by the query planner. Reasonable setting is 1/2 of your total memory.
`checkpoint_segments`: Determines how often PGSQL writes data to disk (in 16MB units). 32-256 is a reasonable range. Set higher values for write-heavy systems.
`work_mem`: Amount of RAM allocated for in-memory sorts and joins. Increase to accelerate reads. **WARNING** This amount is allocated for **each** and **every** sort. Best keep it below 1/100 of your system RAM.

Close this issue when you're happy with your local config.

**Comment by Nuanda** [comment]
@kammerer In case you are interested in optimizing your psql.
