### ISSUE TITLE
Elasticsearch indexing problem with population type

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#171]
When creating the search indices I get this locally:

`org.elasticsearch.index.mapper.MapperParsingException: failed to parse [population_type]`

Can you confirm that on your setup or is it just my local problem?

**Comment by kammerer** [comment]
Probably ES indices need to be rebuilt due to schema changes. Code in app:bootstrap may not do that correctly in such case (it's only my assumption, not a fact).

Try this:

   bin/rake environment elasticsearch:import:model CLASS=PlantLine FORCE=y
   bin/rake environment elasticsearch:import:model CLASS=PlantPopulation FORCE=y

**Comment by Nuanda** [comment]
Should I do that before, after or instead of the app:bootstrap indices building step?

**Comment by kammerer** [comment]
After

2015-04-22 10:14 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Should I do that before, after or instead of the app:bootstrap indices
> building step?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/171#issuecomment-95069814>
> .
>



-- 
Tomasz Szymczyszyn

**Comment by kammerer** [comment]
Sorry, instead, but obviously after will do

2015-04-22 10:16 GMT+02:00 Tomek Szymczyszyn <tomasz.szymczyszyn@gmail.com>:

> After
>
> 2015-04-22 10:14 GMT+02:00 Tomasz Gubała <notifications@github.com>:
>
>> Should I do that before, after or instead of the app:bootstrap indices
>> building step?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/eSpectrum-IT/brassica/issues/171#issuecomment-95069814>
>> .
>>
>
>
>
> --
> Tomasz Szymczyszyn
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
It works - thanks.
