### ISSUE TITLE
PP submission problems

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#176]
- [x] not choosing any PV for new PL results in an error when trying to finalize submission
 - [x] when trying to show the finalized submission I get `undefined method `comments' for nil:NilClass`
 - [x] "entered_by_whom" field is not populated
 - [x] "date_entered" field is not populated
 - [x] also new PL added when submitting a PP has these two annotations missing
 - [x] I'm not sure about new PL's "data_owned_by" field.

**Comment by kammerer** [comment]
Fixed some of the issues, found and fixed one more (reg PV assignment).
"entered_by_whom" is not populated since I wanted to use email however `User#email` is blank (XML info from ORCID does not contain email).

**Comment by Nuanda** [comment]
I'm sorry - I forgot ORCiD does not give us email. So please use user.full_name for all entered_by_whom fields.

**Comment by Nuanda** [comment]
BTW thanks for taking care for that :).
