### ISSUE TITLE
Is SNY1 the same as SYN1 ?

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#18]
I'm checking if all female_parent_line and male_parent_line values inside plant_population tables are really foreign keys to the plant_line table.

The single outstanding value is SNY1. See: http://www.interstoredb.org/Brassica/cs/php/SubpopulationselExcel.php?pop=BnaSNDH

I need your confirmation that it is just a typo and it should read SYN1.

**Comment by sarahcayling** [comment]
Hi,

It certainly looks like a typo, and checking the article listed under data
provenance:
http://www.biomedcentral.com/1471-2164/12/101
Only SYN1 is mentioned.

Best,

Sarah
