### ISSUE TITLE
Take care for routing error problems with glyphicons font files

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#184]

**Comment by bchucherko** [comment]
explanation needed

**Comment by Nuanda** [comment]
When you run the rails server and you open the front page in your browser, in the server logs, you'll see the server is not able to find two or three font files, that are loaded by the view code (stylesheets, most probably).

So either remove the references to these font/glyph files from the view code, if they are not needed, or make sure they are loaded properly.

**Comment by bchucherko** [comment]
Indeed, however I have no control over paths as bootstrap (and glyphicons) isn't an asset visible in any folder. I don't know how exactly it is added to the project (you'll probably know) (right now it points to /fonts/bootstrap/glyphicons-halflings-regular...)
We can add those files as assets manually (same way as other font files) and them import them but I'm not sure if that's a proper way.

**Comment by bchucherko** [comment]
found a solution, fixed with commit 26af6c3
