### ISSUE TITLE
Checking plant_population - plant_line genus and species consistency

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#19]
Next step after #12 and #16 is to get rid of, if possible, columns _genus_ and _species_ from the plant_populations (PP) table. There are three issues connected to that.

1. **No PLs**. As @nowakowski found out, there are 55 PPs that have no assigned plant_line (PL). This is the "commercial line" problem already discussed with @wjurkowski via email.

2. **DIfferent genus**. There are 2 PPs defined as Brassica yet they are linked to 1+ PLs that are set as X_Brassicoraphanus.

3. **Different species**. There are 5 PPs that are not defined as Brassica spp, yet they link to various species of PLs. These PPs are: BolDFS_00, BolDFS_01, BolDFS_04, BolDCC_02, BolEC03_01 (btw all of them are defined as Brassica oleracea, but this is probably a coincidence).

In my opinion, after removal of the genus/species columns from PPs, we should state:
 - unspecified, in case 1
 - various, in case 2
 - Brassica spp, in case 3.

Is that a correct way out?

**Comment by sarahcayling** [comment]
Hi,

Commercial lines will still have genus/species info. Do they not have the
associated data?

Acc to wikipedia:
*Brassicoraphanus* is the name for all the intergeneric hybrids between the
genera Brassica (cabbages, etc.) and Raphanus (radish).
So there are two genus/species but *Brassicoraphanus* is an informative
name, can we list that as the genus?

I imagine that the first 3 are B. oleraceae from the DFF diversity set at
Warwick, I can't think of the acronyms the latter two but I think the use
of Bol is not a coincidence. Can we link that as the species/genus again?

Thanks,

Sarah

**Comment by Nuanda** [comment]
Dear Sarah,

Thanks for the answers.
1. Well, they are not connected to any plant line. The "commercial line" was Wiktor's guess, but this is not confirmed. Anyway, we have no information in the original CS data which would allow as connect those 55 PPs to any PL.

2. Ok, we'll add Brassicoraphanus genus as a "non-canonical" (i.e. not Gramene) entry in our taxonomy terms vocabulary.

3. The problem with the third case is an opposite one. These Plant Populations are connected to Plant Lines already, yet their genus/species information in the plant populations table contradicts (in my opinion) the list of plant lines the record is connected with. The plant population columns state these are oleraceas, yet they are connected with wider set of plant lines (i.e. wider than just oleracea).

On the other hand, this task might not be that important. We wanted to drop genus/species information from the plant population table (to, again, re-normalize it), but perhaps this is counter-productive, and we should stay with what we have now... I guess @nowakowski , when he comes back from his leave, will look into that and decide how to proceed.

**Comment by Nuanda** [comment]
We also need to solve this one way or the other, and rather soon. The simplest solution would be to add PlantPopulation relation to TaxonomyTerm table, map all PPs that have genus/species to correct terms, leave the others blank.
