### ISSUE TITLE
Try to get real CropStore data from the original site administrator

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#2]
It seems data from the bottom of http://cropstoredb.org/description/schema.php#mysql is not the same data as presented in http://www.interstoredb.org/Brassica/cs/ (i.e. some important data are missing in the SQL dump).

Use Wiktor's help in order to get the full data dump from the CropStore site administrator. This is crucial for any further data transformation and integration steps.

**Comment by nowakowski** [comment]
I've sent an appropriate query to WJ.

**Comment by Nuanda** [comment]
Mentioning @wjurkowski so he knows :). Wiktor - tell us when the SQL dump upload to the server is done.
