### ISSUE TITLE
Validations for constraints defined in DB schema are missing

### ISSUE THREAD

**Issue by kammerer** [eSpectrum-IT/brassica#20]
Specifically - a lot of not null constraints is not reflected in validations. Just a reminder as you are probably aware of that.

**Comment by Nuanda** [comment]
Tomek, try to assign someone when posting an issue. Either yourself, or someone, who you think is a better fit for a given work :).

**Comment by Nuanda** [comment]
Also see #36 and #37 when doing this.

**Comment by nowakowski** [comment]
We will be dropping the NN constraints as per #36 so I'm not adding validations atm.
