### ISSUE TITLE
What about past CS curators email addresses?

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#203]
In various CS tables, not only in the `entered_by_whom` metadata column, but also in places like `PlantAccession.accession_originator`, there are email addresses of CS data curators, administrator and maintainers.

There are more or less 4-5 such addresses.

Is that ok for BIP to show these addresses to BIP users? I guess it should be ok, since these are public work addresses - but I want to be completely sure about that, so please confirm.

**Comment by wjurkowski** [comment]
Yes, its fine. Might be useful to contact someone who uploaded the data,
especially if its not linked with any paper.

2015-05-06 17:32 GMT+01:00 Tomasz Gubała <notifications@github.com>:
