### ISSUE TITLE
PlantAccession has two fields that have to undergo some kind of curation

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#204]
There are  `female_parent_plant_id` and `male_parent_plant_id` columns in PlantAccessions (PAs). They have only one distinct value to them (Ningyou 7 and Tapidor).

I guess these are PlantVarieties (PVs). However, PlantLines (PLs) that are referenced by the PAs in question do not, in turn, reference any PVs. Possibilities:
 - turn PA.(fe)male_parent_plant_id into direct PA -> PV relation, and set them to correct PV records (with, obviously, null allowed since many PAs do not have these two relations set)
 - remove PA.(fe)male_parent_plant_id but make sure PLs that are references by these PAs do relate to appropriate PV records.

**Comment by wjurkowski** [comment]
Variety is something catalogued/distinct like any commercial product. If you cross two varieties it doesn't automatically mean that you get a new one. Its an accession and the PV might be empty.
