### ISSUE TITLE
Concerning genotype matrices

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#206]
There's only one record in `genotype_matrices`. Could we ask what the purpose of this record is - and whether you require a GUI for manipulating such records?

**Comment by Nuanda** [comment]
For the time being, we have hidden that table - i.e. the data is still there, you just don't browse it in BIP UI.

**Comment by wjurkowski** [comment]
Well, this is just one genotyping matrix. Definitely there is no need for gui support for this. What is the recommended way to store such matrices?
