### ISSUE TITLE
Nature of LinkageGroup - LinkageMap relation

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#207]
Every LinkageGroup in current data has exactly 1 LinkageMap related to it. However, the schema relation between these two tables is a "many-to-many" relation.

Question: should this relation be reduced to a "many-to-one" relation or is it just a peculiar case of the current CS data and, in the future, any LinkageGroup should be allowed to have many LinkageMaps related to it?

**Comment by wjurkowski** [comment]
Many linkageGroups could be linked to 1 LinkageMap but only one LM should link to LG in question:  yes please turn it to "one-to-many"

**Comment by Nuanda** [comment]
Piotr, please change the relation as suggested. It's a big change since the relating table and model should also be removed. Please, be careful about that migration.

Perhaps a lot of specs will fail after that - please make a PR with the ready migration regardless the failures and assign it to me - I'll try to sort out all problems with upper BIP layers.

**Comment by nowakowski** [comment]
On it.
