### ISSUE TITLE
Probes table curation needed

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#209]
Please:
 - replace `species` column with proper relation to TaxonomyTerm table
 - consider removing `date_described` column, since it is completely blank.

**Comment by Nuanda** [comment]
@nowakowski You removed the `species` column from the Probe model but you didn't remove the validation.

**Comment by nowakowski** [comment]
Right. Stupid omission; sorry. Will fix. Having problems with API rspecs however...

**Comment by Nuanda** [comment]
Try to run bundle install and db:migrate

**Comment by nowakowski** [comment]
No, it's stranger than that; API calls (in `support/shared_examples_api.rb:37`) are returning too many objects. Continuing to investigate.

**Comment by Nuanda** [comment]
rake app:bootstrap ?

**Comment by nowakowski** [comment]
In test env? Surely that shouldn't be required...?

**Comment by kammerer** [comment]
Strange, since ES indices should be rebuilt (effectively, cleaned) before
each test case. Perhaps you have some leftover records in test database?
Have you tried rake db:test:prepare?

2015-05-06 0:13 GMT+02:00 Piotr Nowakowski <notifications@github.com>:

> In test env? Surely that shouldn't be required...?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/209#issuecomment-99247751>
> .
>



-- 
Tomasz Szymczyszyn

**Comment by nowakowski** [comment]
Dropping db:test and recreating it from scratch before each rspec run solves the issue. This didn't happen before.
