### ISSUE TITLE
User plant population submission - question regarding plant lines

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#21]
A question to @wjurkowski .

When submitting her/his plant population, the user interacts with the plant lines table in three places:
 - s/he sets the female parent line
 - s/he sets the male parent line
 - s/he sets the population's plant lines through the intermediate table population lists.

Q1. For now, I assume that in both 1. and 2. cases the user will simply choose an existing plant line. I guess it may also make sense for s/he to be able to define a new plant line for population's parent lines, when suitable lines are not present in our database?

Q2. What is the usual "user story" for the third case? Will users rather add new plant lines along with their population that they submit, or should they at least try to choose some lines from the lines that are currently in the system? Should we somehow "encourage" them to choose from existing lines or is it rather they will file new plant lines, since this is the core of submitting a new population? While exploring current population_lists table I discovered some plant lines are connected to as many as 6 different populations, so I guess there is some reuse there.

**Comment by sarahcayling** [comment]
Q1. Users will need to add new parents, would there be a way to suggest
existing parents if they have a similar name to reduce typos?

Q2. Plant lines being reused in populations - I guess that won't be true of
crosses (as this is your genealogy, you only have 2 parents and a set of
siblings) but might be true if people are using this more as a 'set' of
lines for an experiment. Let me take a look at the data and get back on
this one. Heading to a full afternoon meeting, so I won't be able to do
much today...

**Comment by Nuanda** [comment]
Sarah - thanks for the answers.

Q1. Ok, we will try to help the users with choosing proper PL before they decide to add their own.

Q2. Again, we will let the user to choose a set of PLs for his/her particular plant population, but we will also let her/him add new PLs if needed.

**Comment by Nuanda** [comment]
Tomek, please take the above into consideration when designing the user plant population submission workflow.

**Comment by Nuanda** [comment]
Taken into consideration and implemented.
