### ISSUE TITLE
Implement create API

### ISSUE THREAD

**Issue by kammerer** [eSpectrum-IT/brassica#218]
Validation should handle misnamed attributes.

**Comment by kammerer** [comment]
Partially implemented. Issues / questions:

* We should improve model validations, e.g. there are no uniqueness validations / unique indices on some fields which I think should be unique such as `PlantPopulation#name`. Should I add these?
* Many-to-many relationships - not sure if it is better to handle them transparently and allow pass array of ids or expose join table in the API.

**Comment by Nuanda** [comment]
@nowakowski agreed to do that.

**Comment by Nuanda** [comment]
Regarding M-to-N relationships - I think it depends on whether there are data (apart from fkeys) stored in the join table or not.

**Comment by kammerer** [comment]
Right now we have one HABTM join table with column other than PKs - `plant_population_lists.sort_order`.
It does not have a PK though so it can't be exposed in the API. According to RoR docs for `has_and_belongs_to_many` "the join table should not have a primary key or a model associated with it." I am not sure if adding a PK would really be a problem but I suppose it would be safer to change this to a `has_many` relationship with `:through` option and add `id` column.

BTW `sort_order` column is not used anywhere and is not populated in submission. It has wrong type too. Should I add tickets to fix this?

There is also a problem with `MapLinkageGroupList` model which is used as a join model for `has_many :through`. It has a `comments` fields with no values present and it does not have a PK.

**Comment by Nuanda** [comment]
Please do file issues (or a single issue) for that. We definitely can get rid of comments in ML-MG join table, I wasn't sure about the sort order - perhaps there already has been some discussion on that? @nowakowski Piotr, please take care of that.

**Comment by kammerer** [comment]
Make sure objects created by API store info about user which created them.

**Comment by Nuanda** [comment]
Related to #278
