### ISSUE TITLE
API sandbox mode

### ISSUE THREAD

**Issue by kammerer** [eSpectrum-IT/brassica#219]
@Nuanda I got another idea, even simpler that sandbox mode we discussed earlier - I mean something like a dry-run flag in Unix commands. I.e. when you submit a dry-run request you see its results in the response  but that change is immediately discarded. 
This approach certainly is more limited since it only allows developer to verify one step ahead but it seems to be **a lot** easier to implement.

**Comment by Nuanda** [comment]
I'm not sure what is the added value here, perhaps I'm not seeing what you mean. We are going to have model validations, so any API submission violating these will not affect the database anyway (and the user will be notified accordingly).

When all validations are ok, using the dry-run will simply output what user has provided in the submission API call.

So, perhaps, a better solution is to simply have all validations in place (i.e. where they are needed) and good error messages returned to the user when something is not right?

Unfortunately, due to extremely permissive nature of the original CS model wrt relations (esentially, all relations in CS are optional!), we are still not sure which BIP model relations should be required and which ones could be set as optional. But this is something @nowakowski needs to take care of anyway.

**Comment by kammerer** [comment]
Of course we will have validations, however my original concern was about
mistakes which would not be covered by them (not errors strictly speaking),
e.g. misspelled optional attribute names - in dry-run user would see that
the response data is different than request data.

I admit that there is limited added value with this approach, maybe it is
not sensible at all. The example issue I mentioned before could be handled
by somewhat extended validation layer returning info about unrecognised
input.

2015-05-04 10:44 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> I'm not sure what is the added value here, perhaps I'm not seeing what you
> mean. We are going to have model validations, so any API submission
> violating these will not affect the database anyway (and the user will be
> notified accordingly).
>
> When all validations are ok, using the dry-run will simply output what
> user has provided in the submission API call.
>
> So, perhaps, a better solution is to simply have all validations in place
> (i.e. where they are needed) and good error messages returned to the user
> when something is not right?
>
> Unfortunately, due to extremely permissive nature of the original CS model
> wrt relations (esentially, all relations in CS are optional!), we are still
> not sure which BIP model relations should be required and which ones could
> be set as optional. But this is something @nowakowski
> <https://github.com/nowakowski> needs to take care of anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/219#issuecomment-98638233>
> .
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
Regarding the issue you mention - in another API we were developing recently we had strict check for extra (i.e. not expected) attributes in API write calls. That would guard against the "misspelled names case" you mentioned.

Would it be possible (and not difficult) to add such a simple check on API write calls?

**Comment by kammerer** [comment]
Possible and rather easy.

2015-05-04 11:12 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Regarding the issue you mention - in another API we were developing
> recently we had strict check for extra (i.e. not expected) attributes in
> API write calls. That would guard against the "misspelled names case" you
> mentioned.
>
> Would it be possible (and not difficult) to add such a simple check on API
> write calls?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/219#issuecomment-98644131>
> .
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
Ok Tomasz, let us do that first. So:
 - making sure validations are run and user gets proper validation errors
 - checking if there are no extra parameters to the written object JSON.

And we will deal with dryrun/sandbox modes later. I still prefer the original "temporary tables" idea, but we may want to finish other parts of the system first.

Anyway, please leave implementation of the API write calls for now. We are still waiting for TGAC to solve the "IsaTab - MIAPPE - Excel data - CS model" problem before we can proceed with the submission part, and API write calls can only come after the submission is in place.

**Comment by kammerer** [comment]
ACK

2015-05-04 11:22 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Ok Tomasz, let us do that first. So:
>
>    - making sure validations are run and user gets proper validation
>    errors
>    - checking if there are no extra parameters to the written object JSON.
>
> And we will deal with dryrun/sandbox modes later. I still prefer the
> original "temporary tables" idea, but we may want to finish other parts of
> the system first.
>
> Anyway, please leave implementation of the API write calls for now. We are
> still waiting for TGAC to solve the "IsaTab - MIAPPE - Excel data - CS
> model" problem before we can proceed with the submission part, and API
> write calls can only come after the submission is in place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/219#issuecomment-98648750>
> .
>



-- 
Tomasz Szymczyszyn
