### ISSUE TITLE
Setup the development server and deployment procedure

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#22]
While waiting for #6 fix (the long delay in connection establishment) please start to setup the server according to our needs.

**Comment by kammerer** [comment]
Almost done, I have emailed you with the main remaining issue.

**Comment by Nuanda** [comment]
Statics from public subfolders are not served properly. We have Rails static support switched off, as it should be, but Nginx does not take over that responsibility. I think this is because the location configuration tells Rails to take care for everything apart from the `assets` subfolder.

I made simple fixes to the nginx configuration, bet perhaps you'd like to take a look at it in order you'd prefer it some other way.

**Comment by kammerer** [comment]
Reminder to self: configure HTTPS.

**Comment by Nuanda** [comment]
I reconfigured our proxy so you should be able to test ORCiD auth on the TGAC server and you should also be able to access https webpages - so setting that up should be possible now.

**Comment by kammerer** [comment]
Enabled HTTPS.

**Comment by Nuanda** [comment]
Do you think we should force all of the traffic via https?

**Comment by kammerer** [comment]
For signed in users and API it makes sense. Otherwise I am not sure.

2015-05-11 19:34 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Do you think we should force all of the traffic via https?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/22#issuecomment-100987584>
> .
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
[They say](https://www.youtube.com/watch?v=cBhZ6S0PFCY) let's make it all https :).

**Comment by Nuanda** [comment]
Tomasz, I wonder whether `brassica/brassica` and brassica/current.old` dirs on our server are still of any use. If not, please remove them.

Another question is about logs rolling - do we take care in any way for logs growing too large or not yet?

**Comment by Nuanda** [comment]
I switched nginx to serve Brassica on HTTPS only - see internal docs for documented config change.

Also filed separate issue to remember to roll logs after final deployment: #286

**Comment by kammerer** [comment]
Removed `brassica/brassica` and `brassica/current.old` dirs.

**Comment by kammerer** [comment]
Log rolling is not configured yet.

**Comment by Nuanda** [comment]
We will do that after the final deployment. I do hope we will use the same server as that would save us a lot of fiddling with settings. Still waiting for @wjurkowski response as to how should we proceed with respect to the audit.

**Comment by Nuanda** [comment]
Apart from log rolling please also setup a puma monitoring/restart solution. We need everything to start properly after system reboot.

**Comment by kammerer** [comment]
I have found issues with puma/jungle scripts as they are prepared for debian-based distros. After some research I decided to use monit to start and supervise puma process (it can be used for other things too). I have not finished monit setup yet.

**Comment by kammerer** [comment]
Puma monitoring is ready. Monit will start it after reboot or crash. Sending alerts does not yet work as there are issues with MTA.

**Comment by Nuanda** [comment]
I have adjusted the server nginx settings to use the domain name (bip.tgac.ac.uk) so no explicit IP address is needed anymore (that is, in the browser address bar).

**Comment by Nuanda** [comment]
Please don't forget to add the monit task to purge cache in case of disk space shortage.

**Comment by kammerer** [comment]
Done. Cleanup triggered at 50%.

2015-07-31 16:52 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Please don't forget to add the monit task to purge cache in case of disk
> space shortage.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/22#issuecomment-126716282>
> .
>



-- 
Tomasz Szymczyszyn
