### ISSUE TITLE
ORCID signup issue - CSRF detected

### ISSUE THREAD

**Issue by kammerer** [eSpectrum-IT/brassica#226]
Despite getting this error message I got signed in (development server on lvh.me:3000).

> Could not authenticate you from ORCID. Reason: "Csrf detected". 

![orcid](https://cloud.githubusercontent.com/assets/14025/7482867/a0725f48-f37a-11e4-8117-0d5e16c4aae8.png)

**Comment by Nuanda** [comment]
#153  I saw it before but then it disappeared. It seems the problem is still there.

**Comment by wjurkowski** [comment]
I saw it only before completing activation in confirmation email. After
completing registration this message disappeared

2015-05-05 22:33 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Test again after final deployment, esp. with the final domain name.

**Comment by Nuanda** [comment]
Tested on the final deployment in FF, Chrome, Safari, IE10 - seems not to appear anymore.
