### ISSUE TITLE
Provide proper way of relating MapPosition and MapLocusHits

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#228]
The best way would be to use existing column data to introduce proper 1-N or N-M relationship and then drop the redundant columns.

If not possible, some other hack would be needed.

**Comment by nowakowski** [comment]
Okay, here's what I did - @sarahcayling, please correct me if I'm wrong, and also (if possible) provide an answer to the question below:

  - I added a numerical primary key (`id`) in `map_positions` and created a foreign key in `map_locus_hits` linking to `map_positions.id`.
  - In order to infer proper values for the new FK I iterated over `map_locus_hits` and for each record I attempted to find a corresponding `map_positions` record which meets the following criteria:
    - it links to the same `population_locus` as the source `map_locus_hits` record
    - it links to the same `linkage group` as the source `map_locus_hits` record
    - its value of the `map_position` field is identical to that in the source `map_locus_hits` record

This operation was successful for nearly all `map_locus_hits` (6391 records out of 6504), however there are 113 `map_locus_hits` records for which no corresponding `map_position` could be found:

  - In 23 `map_locus_hits` records the `map_position` field is NULL
  - In 90 `map_locus_hits` records all necessary data (population locus ID, linkage group ID, map position) is present but no corresponding `map_positions` record exists in the database.

My question is - what to do about these records? Should we leave them unbound to any `map_positions`, delete them or attempt curation?

**Comment by nowakowski** [comment]
For reference: the following `map_locus_hits` do not appear to correspond to any `map_positions` record in the DB:

 mapping_locus | linkage_group_label  | map_position 
---------------|----------------------|--------------
 pE335e4       | BolAGDH_01_1999b_AG6 | 2.0
 pE127e1       | BolAGDH_01_1999b_AG3 | 35.0
 pE598e2       | BolAGDH_01_1999b_AG7 | 75.0
 pE764e1       | BolAGDH_01_1999b_AG8 | 10.0
 pWG1G2e1      | BolAGDH_01_1999b_AG9 | 70.0
 pE349e1       | BolAGDH_01_1999b_AG4 | 3.0
 pWG1G7e1      | BolAGDH_01_1999b_AG2 | 52.0
 pE335e1       | BolAGDH_01_1999b_AG2 | 35.0
 pE335e3       | BolAGDH_01_1999b_AG3 | 23.0
 pWG7F3e2      | BolAGDH_01_1999b_AG2 | 48.0
 pE567e1       | BolAGDH_01_1999b_AG1 | 69.0
 pWG4D11e1     | BolAGDH_01_1999b_AG2 | 51.0
 pE323e1       | BolAGDH_01_1999b_AG8 | 1.0
 pE757e1       | BolAGDH_01_1999b_AG5 | 14.0
 pWG5A6e2      | BolAGDH_01_1999b_AG2 | 52.0
 pE647e2       | BolAGDH_01_1999b_AG8 | 78.0
 pE128e3       | BolAGDH_01_1999b_AG5 | 2.0
 pE128e1       | BolAGDH_01_1999b_AG8 | 77.0
 pE202e1       | BolAGDH_01_1999b_AG1 | 31.0
 pE709e4       | BolAGDH_01_1999b_AG2 | 81.0
 pE724e2       | BolAGDH_01_1999b_AG2 | 81.0
 pE724e1       | BolAGDH_01_1999b_AG9 | 36.0
 pE262e3       | BolAGDH_01_1999b_AG1 | 12.0
 pE262e2       | BolAGDH_01_1999b_AG3 | 98.0
 pE262e1       | BolAGDH_01_1999b_AG7 | 55.0
 pE157e2       | BolAGDH_01_1999b_AG9 | 1.0
 pE625e3       | BolAGDH_01_1999b_AG1 | 35.0
 pWG6B10e1     | BolAGDH_01_1999b_AG2 | 47.0
 pE196e2       | BolAGDH_01_1999b_AG4 | 41.0
 pE765e2       | BolAGDH_01_1999b_AG3 | 20.0
 pE765e1       | BolAGDH_01_1999b_AG9 | 73.0
 pWG5B1e2      | BolAGDH_01_1999b_AG2 | 51.0
 pWG5B1e1      | BolAGDH_01_1999b_AG3 | 55.0
 pE777e1       | BolAGDH_01_1999b_AG3 | 83.0
 pE192e2       | BolAGDH_01_1999b_AG8 | 1.0
 pWG6C1e1      | BolAGDH_01_1999b_AG2 | 61.0
 pE776e1       | BolAGDH_01_1999b_AG4 | 20.0
 pWG2C3e1      | BolAGDH_01_1999b_AG2 | 47.0
 pE728e1       | BolAGDH_01_1999b_AG5 | 60.0
 pWG5A1e1      | BolAGDH_01_1999b_AG6 | 35.0
 pE617e1       | BolAGDH_01_1999b_AG3 | 94.0
 pE126e1       | BolAGDH_01_1999b_AG8 | 79.0
 pWG6F3e1      | BolAGDH_01_1999b_AG9 | 56.0
 pTG2B4e1      | BolAGDH_01_1999b_AG6 | 5.0
 pE278e1       | BolAGDH_01_1999b_AG8 | 63.0
 pWG6G9e1      | BolAGDH_01_1999b_AG3 | 105.0
 pTG6A12e1     | BolAGDH_01_1999b_AG3 | 78.0
 pWG3H8e1      | BolAGDH_01_1999b_AG9 | 57.0
 pWG4A4e1      | BolAGDH_01_1999b_AG4 | 81.0
 pWG6F10e2     | BolAGDH_01_1999b_AG4 | 36.0
 pWG6F10e1     | BolAGDH_01_1999b_AG8 | 31.0
 pWG6B2e1      | BolAGDH_01_1999b_AG3 | 26.0
 pE328e3       | BolAGDH_01_1999b_AG3 | 72.0
 pTG2D6e1      | BolAGDH_01_1999b_AG3 | 37.0
 pE276e1       | BolAGDH_01_1999b_AG2 | 20.0
 pTG4D2e1      | BolAGDH_01_1999b_AG5 | 32.0
 pE861e1       | BolAGDH_01_1999b_AG3 | 82.0
 pWG2B7e1      | BolAGDH_01_1999b_AG5 | 20.0
 pE107e1       | BolAGDH_01_1999b_AG5 | 83.0
 pWG4B6e1      | BolAGDH_01_1999b_AG3 | 86.0
 pE275e2       | BolAGDH_01_1999b_AG4 | 24.0
 pE640e1       | BolAGDH_01_1999b_AG7 | 8.0
 pWG1D7e2      | BolAGDH_01_1999b_AG3 | 62.0
 pWG1D7e1      | BolAGDH_01_1999b_AG5 | 85.0
 pWG8G3e1      | BolAGDH_01_1999b_AG6 | 8.0
 pWG6A10e2     | BolAGDH_01_1999b_AG4 | 23.0
 pWG6A10e1     | BolAGDH_01_1999b_AG9 | 24.0
 pWG8A9e3      | BolAGDH_01_1999b_AG3 | 45.0
 pWG8A9e1      | BolAGDH_01_1999b_AG4 | 101.0
 pE748e1       | BolAGDH_01_1999b_AG5 | 28.0
 pWG6A12e1     | BolAGDH_01_1999b_AG4 | 73.0
 pE118e1       | BolAGDH_01_1999b_AG1 | 77.0
 pWG7B3e1      | BolAGDH_01_1999b_AG9 | 73.0
 pWG1G5e1      | BolAGDH_01_1999b_AG1 | 71.0
 pTG5H12e1     | BolAGDH_01_1999b_AG5 | 19.0
 pWG3F7e1      | BolAGDH_01_1999b_AG9 | 103.0
 pWG1E3e1      | BolAGDH_01_1999b_AG3 | 73.0
 pWG1E3e3      | BolAGDH_01_1999b_AG8 | 29.0
 pTG5B2e1      | BolAGDH_01_1999b_AG7 | 49.0
 pTG5B2e2      | BolAGDH_01_1999b_AG8 | 24.0
 pWG6A11e1     | BolAGDH_01_1999b_AG5 | 24.0
 pWG6A11e2     | BolAGDH_01_1999b_AG8 | 10.0
 pWG8H9e1      | BolAGDH_01_1999b_AG9 | 64.0
 pWG3C5e1      | BolAGDH_01_1999b_AG5 | 23.0
 pE256e1       | BolAGDH_01_1999b_AG7 | 32.0
 pE710e1       | BolAGDH_01_1999b_AG5 | 14.0
 pWG7A11e1     | BolAGDH_01_1999b_AG3 | 69.0
 pWG2C4e1      | BolAGDH_01_1999b_AG7 | 3.0
 pWG7A8e1      | BolAGDH_01_1999b_AG2 | 74.0
 pE584e1       | BolAGDH_01_1999b_AG7 | 52.0

**Comment by nowakowski** [comment]
Leaving unbound records in the table for future curation.
