### ISSUE TITLE
Front matter information

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#23]
It would help us to know what information you would like to have on the front page of BIP. Currently i was thinking that we may have a single paragraph introduction to BIP presented to the user right away, and then a longer, single page description of BIP, TGAC etc. in a dedicated "about us" or "tell me more" page.

If this is ok with you (@sarahcayling @wjurkowski), please try to provide us the introductory text for the front page. It is important from the layouting point of view to know how much text you'd like to have there and in what parts. Having your initial input we may try to come up with a placement proposition.

**Comment by wjurkowski** [comment]
This sounds good for start - we will collect additional feedback tomorrow

The text could be very brief leaving space for clear access to "browse phenotypes"; "browse genome"; "search"; "tools" 

"Welcome to Brassica Information Portal (BIP). The BIP builds on CropStore, BrassEnsembl and other data resources developed at Warwick and Rothamsted Research. It incorporates additional data types and novel interfaces to enable enhanced knowledge discovery across multiple Brassica species."

**Comment by Nuanda** [comment]
This text sounds to me a little bit more suitable for the following, "About us" page, not for the front page. But we will put it there if you think it's important to have this message on the front page.
