### ISSUE TITLE
Problem with lack of proper MLH table primary key(?)

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#233]
I think this is related to the lack of PKEY in that table, but perhaps the cause is different. Anyway, doing a simple operation like that:

`LinkageGroup.first.map_locus_hits << MapLocusHit.first`

results in:

`TypeError: nil is not a symbol nor a string`

exception. Can you please try to find out what is happening there?

**Comment by nowakowski** [comment]
OK, it seems that this indeed occurs because `map_locus_hits` lacks an obvious primary key. RoR 4 cannot deal with tables which do not have a PK. I will introduce a PK now so you no longer run into this error, then work on figuring out a way to properly relate MLH with LM.
