### ISSUE TITLE
Handle ES special characters / syntax in search query

### ISSUE THREAD

**Issue by kammerer** [eSpectrum-IT/brassica#247]
The user input we collect in search gets passed to ES with small modifications only. This may cause ES to fail in case user enters something which ES recognizes as its own query string syntax but is not valid.

We should decide what power we give to users in terms of customizing search results, if any at all. The most straightforward option would be to strip / escape unwanted input. 

http://www.elastic.co/guide/en/elasticsearch/reference/1.x/query-dsl-query-string-query.html

**Comment by Nuanda** [comment]
Please block anything except the special cases I wrote you about. I assume the leading and trailing wildcards are added by default (i.e. any query string becomes \*string\*).
