### ISSUE TITLE
Do not wildcard numeric fields in global search

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#253]
Example: `map_locus.map_locus = "102.5"`

This should come up in search by "102.5" but it should not when one looks for "2.5" or "2". I can supply you with a set of fields that should be treated this way.

Wait for #242 before doing that. Also related to #225.

**Comment by kammerer** [comment]
What about searching for "10" or "102"?

**Comment by Nuanda** [comment]
Well, `10` still does not make much sense. I also was thinking about right hand side wildcard, but then again it would need to be smarter than that, and be able to detect periods. Also, one never knows is "102" is almost as good as "102.5" in a given case, as as bad as "555" - since you never know the actual distance :).

So, let's have the simple exact match, if possible.

**Comment by Nuanda** [comment]
Can you tell me if that is possible? Because if that is the case, I will prepare the list of fields for you.

**Comment by kammerer** [comment]
I am pretty sure it is possible. I have a vague idea how it could be done
but I will need to test it.

2015-05-13 21:10 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Can you tell me if that is possible? Because if that is the case, I will
> prepare the list of fields for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/253#issuecomment-101780194>
> .
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
So, for testing, you can use Qtl model. This rule would apply to:
```
      'qtl_rank',
      'outer_interval_start',
      'inner_interval_start',
      'qtl_mid_position',
      'inner_interval_end',
      'outer_interval_end',
      'peak_value',
      'peak_p_value',
      'regression_p',
      'residual_p',
      'additive_effect',
      'genetic_variance_explained'
```

**Comment by Nuanda** [comment]
Actually there is only one further column: map_position.map_position. Please add it in the respective PR.
