### ISSUE TITLE
Fix wrong behavior of left-hand menu in API docs section

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#255]
Wrong section highlighting.

**Comment by bchucherko** [comment]
Fixed

**Comment by Nuanda** [comment]
The menu is now considerably longer and this issue has to be addressed again. @bchucherko Bartosz, can it be fixed the way it works no matter how long the menu is?

**Comment by Nuanda** [comment]
Hmm, looks ok on Firefox. Would it be just a chromium problem?

**Comment by Nuanda** [comment]
Thanks for fixing this.
