### ISSUE TITLE
PlantVarieties table has wrong line wrapping in IE11

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#260]
URL is `/data_tables?model=plant_varieties`

In IE11 the `Quoted parentage` column does no wrap text inside correctly (the table gets very wide...). Can you help with that?

**Comment by Nuanda** [comment]
Not every page has that (depends on the records being displayed). Sort by `Attribution` to see the problem.

**Comment by bchucherko** [comment]
Blink/webkit/gecko browsers somehow deal automatically with very long rows, unfortunately IE does not.
There's no easy solution of this that I now of except setting:
-ms-word-break: break-all;
This will trigger breaking words on width limit, resulting in breaking one very long strings, however, this will cause breaking of other words in places where they really shouldn't.

**Comment by bchucherko** [comment]
OK, I found a solution - it's not perfect but definitely better than now.

**Comment by bchucherko** [comment]
Fixed

**Comment by Nuanda** [comment]
Deployed to production. Will test it later tonight.
