### ISSUE TITLE
Primers: sequence_source_acronym and sequence_id contain no useful data

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#263]
I spotted the `primers` table has two columns that contain only a single, placeholder value. These are `sequence_source_acronym` and `sequence_id`.

Will they play any role in BIP wrt user-submitted data? If not, I propose to remove them.

**Comment by Nuanda** [comment]
Since no defense was offered so far for these two columns, I am going to delete them :).

**Comment by Nuanda** [comment]
Decided to leave them be for now. I see a similar fields in the probes table being used, so perhaps also here they will be put to some use later.

**Comment by wjurkowski** [comment]
In fact the whole table is almost empty and only three columns are being used effectively. I guess we could remove the non-used columns. On the other hand information about the manufacturer of the kit is missing. Maybe one of it was for that purpose?

**Comment by Nuanda** [comment]
I think the purpose of this two fields might be similar to how they are used in the primers table.
