### ISSUE TITLE
Datatable view improvements

### ISSUE THREAD

**Issue by kammerer** [eSpectrum-IT/brassica#265]
I want to suggest two improvements for data-table.

1. Showing search query along with search results would make it clear what is going on.
2. "Related" button could be disabled if there are no related object so that user knows it is not worth clicking.

![datatable](https://cloud.githubusercontent.com/assets/14025/7564566/46b071d0-f7e8-11e4-8721-f8aaa94d6250.png)
 view

**Comment by wjurkowski** [comment]
I like the idea of showing the query. Not sure of the related button. What
is the definition of relation in 'related'?

2015-05-11 13:18 GMT+01:00 Tomasz Szymczyszyn <notifications@github.com>:

**Comment by Nuanda** [comment]
Oh, you can check that in the BIP deployment :). Basically, this allows the user to navigate "to many" relationship of a given table record (but sometimes more than that).

**Comment by wjurkowski** [comment]
OK, I'l try it. I like the idea just not sure whether the relationship is
something the user can define or it pos automatically e.g. relationship by
study, common variety etc.

2015-05-12 8:55 GMT+01:00 Tomasz Gubała <notifications@github.com>:
