### ISSUE TITLE
Population canonical names vs. plant population names  - what do we really need?

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#27]
This is important for both population data browsing and population data submission. Current CS plant population data (see e.g. http://www.interstoredb.org/Brassica/cs/) have two "naming" columns: plant_population_name (ppn) and canonical_population_name (cpn). I see two cases here:
 - ppn reads BolAGDH_04 and then cpn equals BolAGDH (no unique number postfix)
 - ppn is blank and then cpn is sth like GRC_AZE005 (essentially, taking the role of unique identifier).

Do we really need both of them or is just the way the CS author wanted to manage his data? Could we perhaps merge them into one, using ppn (in the 1st case above) or cpn (in the 2nd case) value for a user-readable, unique identifier?

We may also want to leave it like it is, but then we need to explain the difference to the users and help him/her submit both names in the submission form. It looks to me like, perhaps, an unnecessary complication of the process... Maybe a single, unique plant population name is enough?

Please, tell me what you think.

**Comment by Nuanda** [comment]
I understand the decision is (we talked a bit about that during our teleconf) that we need to keep the Canonical name as well. If no further comments, I will distribute tasks regarding that.

**Comment by wjurkowski** [comment]
I'd strongly advocate for one population name as and unique identifier if
possible incorporating canonical name. It should never be blank. If we
could have some kind of schema we could remove cpn e.g.:

canonical_instance e.g. BolAGDH_04

In case of missing info:

NA_something

I suspect again some kind of error in GRC_AZE005 assigned as cpn. Perhaps
this is was supposed to be ppm and canonical is missing not the other way
around.



2015-03-28 10:25 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
@nowakowski This is another problem with the PP model that we need to solve soon - since it takes too long for the good of the project. Please take it from here and conclude, hopefully today or tomorrow.

**Comment by nowakowski** [comment]
Fixed by #102
