### ISSUE TITLE
What is the difference between 'bac' and 'atg' fields in map_locus_hits

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#275]
Could you tell us what these acronyms stand for?

**Comment by Nuanda** [comment]
We have linked `atg` sequence identifier to the ensembl service. Still don't know what to do with the other one.

**Comment by Nuanda** [comment]
All right, I realized also the `sequence_id` and `bac` ids are in fact NCBI's identifiers. I added NCBI links to these columns as well. BTW I also added same links in `Probes.sequence_id` column.

The only thing left that I don't know where to link to are 'MLH.sequence_id` for which the sequence source acronym was set to: RRES_SQS_BRASS_xxxx. Any idea where these point to?
