### ISSUE TITLE
Make submissions more population-oriented.

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#29]
Currently we don't know how the submission module will be decomposed (see #24), but for the first prototype I propose to assume, for the time being, that user can only submit plant populations.

Therefore:
- [x] change button label "Submit new research data" to "Submit plant population"
- [ ] change the information in the submissions list items to what I describe below
- [x] change each step title from "Submission details" to "Plant population submission"

The proposition of the submission item list information:

Population: BraCKDH (B. rapa). DH segregating. Parents: Chiifu type 401-42 | Kenshin type 402-43.

That is population name, species, type (if present), parents (if present). Then "submitted on (date)" or "last modification (date)", depending on the current submission state and the "submitted" label or actions buttons, like it is shown now.

**Comment by kammerer** [comment]
@Nuanda As for *species*, is it OK if I:

* put B. + species for Brassica (make it a special case where genus can be shortened)
* put X_Brassicoraphanus as a whole word
* omit in case of "none", "undefined", "not_applicable"

**Comment by Nuanda** [comment]
Yes, that is ok.

**Comment by Nuanda** [comment]
It looks like merging #11 closed this yet there is still one tick to do. Perhaps i shouldn't merge that PR, even though it was marked ready for review? Anyway, reopening this just to be sure.

**Comment by kammerer** [comment]
That's because I added "Fixes..." in commit message (being too hasty).
