### ISSUE TITLE
Reset the database after deployment

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#298]

**Comment by kammerer** [comment]
You mean that `rake app:bootstrap` should be run instead of migrations?

**Comment by Nuanda** [comment]
No no - just that I did a lot of submission testing so I submitted some false data to the DB. We simply have to make sure these things are deleted when the BIP goes public.

**Comment by Nuanda** [comment]
DB was reset and populated with CS data afresh.

**Comment by Nuanda** [comment]
Do the reset again after tests.
