### ISSUE TITLE
Changes in PP submission process forms and data fields

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#30]
Let's have the field a little bit more descriptive:
- [x] 1/4. Owned by -> Population owned by
- [x] 2/4. Hide, for now, everything besides the population type (we will use that taxonomy choice later - when adding a new plant line)
- [x] 3/4. After parent plant lines add another section called population plant line list. There allow the user to "stack" population lines, by choosing from current ones and adding to the list.

**Comment by kammerer** [comment]
@Nuanda You say "stack", is order important then?

**Comment by kammerer** [comment]
How about something like this [this](http://awesomescreenshot.com/0804k1ykf7)?

Note 1: I assumed these three plant line fields are required based on current not-null constraints in the DB.
Note 2: Select-autocomplete widget is simplified. I think it should show more fields both for selected items and search results.

**Comment by Nuanda** [comment]
Order might be not important. This concept looks ok - let's go with this.

**Comment by kammerer** [comment]
@nowakowski @Nuanda 
1. Can you tell what fields really are required in order to define new PL?
2. Should I allow to define PL by choosing a TT?

**Comment by Nuanda** [comment]
Actually you should not allow users to define their own genus, species, subtaxa for a new PL, but only allow them to choose a present TT (as a relation). Regarding the fields:
 - required: plant_line_name, taxonomy_term_id (see above)
 - optional: common_name, previous_line_name, comments, genetic_status (here maybe an autocomplete with possibility to type in one's own term?), named_by_whom, organisation (also an autocomplete?)
 - entered_by_whom, data_provenance, data_owned_by - copy from PP submission
 - plant_variety_name - ignore, will not be used anymore.
