### ISSUE TITLE
Display problem with blue buttons in the data table (IE11)

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#301]
Win7, IE11. The data tables where we have both the related and the metadata buttons, here these two melted together in IE11. This, I believe, may also cause the table being slightly too wide, even where there is hardly any data to be displayed. No such problem on Chrome, Win7. See attached screenshots for comparison.

Is it possible to fix that with css?

![bip_ie11](https://cloud.githubusercontent.com/assets/107565/7919047/f1b25d92-0895-11e5-984b-2f2d6f120279.png)

![bip_chrome](https://cloud.githubusercontent.com/assets/107565/7919056/f99cb174-0895-11e5-8a83-2b6151d6b9bc.png)

**Comment by bchucherko** [comment]
This bug is a rasult of another fix #260 - fixed positioning for IE11 introduces this bug. For deleting mentioned fix helps and is recommended, however will be back to wrapping long lines problem. I haven't found another solution to this though.

**Comment by Nuanda** [comment]
But wouldn't that be enough to not apply `word-wrap: break-word;` style to the last `th` and `td` with buttons (through some kind of more specific selector)?

**Comment by bchucherko** [comment]
No, problem is within fixed positioning on table element.
I wanted to check again issue #260 however I cannot reproduce the issue any longer.

**Comment by Nuanda** [comment]
It depends on the exact set of records you are seeing in the table. The issue manifests itself when you try to sort by different columns, so some long-value text fields appear in the table, and are not wrapped correctly.
