### ISSUE TITLE
Classify all BIP table relations as either mandatory or optional

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#314]
The following is a dump of all BIP model tables and relation columns (regular attributes have been omitted). For each relation column, please provide information on whether the relevant relation is mandatory (i.e. a child object *must* have a parent object assigned) or optional (a child object can be valid even when the parent object is NULL).

```
# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20150608102750) do

  create_table "countries", force: :cascade do |t|
  end

  create_table "design_factors", force: :cascade do |t|
  end

  create_table "genotype_matrices", force: :cascade do |t|
    t.integer "linkage_map_id"
  end

  create_table "linkage_groups", force: :cascade do |t|
    t.integer "linkage_map_id"
  end

  create_table "linkage_maps", force: :cascade do |t|
    t.integer "plant_population_id"
  end

  create_table "map_locus_hits", force: :cascade do |t|
    t.integer "linkage_map_id"
    t.integer "linkage_group_id"
    t.integer "population_locus_id"
    t.integer "map_position_id"
  end

  create_table "map_positions", force: :cascade do |t|
    t.integer "linkage_group_id"
    t.integer "population_locus_id"
  end

  create_table "marker_assays", force: :cascade do |t|
    t.integer "restriction_enzyme_a_id"
    t.integer "marker_sequence_assignment_id"
    t.integer "restriction_enzyme_b_id"
    t.integer "primer_a_id"
    t.integer "primer_b_id"
    t.integer "probe_id"
  end

  create_table "marker_sequence_assignments", force: :cascade do |t|
  end

  create_table "plant_accessions", force: :cascade do |t|
    t.integer "plant_line_id"
  end

  create_table "plant_lines", force: :cascade do |t|
    t.integer  "taxonomy_term_id"
    t.integer  "plant_variety_id"
  end

  create_table "plant_parts", force: :cascade do |t|
  end

  create_table "plant_population_lists", id: false, force: :cascade do |t|
    t.integer "plant_line_id"
    t.integer "plant_population_id"
  end

  create_table "plant_populations", force: :cascade do |t|
    t.integer  "taxonomy_term_id"
    t.integer  "male_parent_line_id"
    t.integer  "female_parent_line_id"
    t.integer  "population_type_id"
  end

  create_table "plant_scoring_units", force: :cascade do |t|
    t.integer "plant_accession_id"
    t.integer "plant_trial_id"
    t.integer "design_factor_id"
    t.integer "plant_part_id"
  end

  create_table "plant_trials", force: :cascade do |t|
    t.integer "country_id"
    t.integer "plant_population_id"
    t.integer "pubmed_id"
  end

  create_table "plant_varieties", force: :cascade do |t|
  end

  create_table "plant_variety_country_of_origin", id: false, force: :cascade do |t|
    t.integer "country_id"
    t.integer "plant_variety_id"
  end

  create_table "plant_variety_country_registered", id: false, force: :cascade do |t|
    t.integer "country_id"
    t.integer "plant_variety_id"
  end

  create_table "pop_type_lookup", force: :cascade do |t|
  end

  create_table "population_loci", force: :cascade do |t|
    t.integer "plant_population_id"
    t.integer "marker_assay_id"
  end

  create_table "primers", force: :cascade do |t|
  end

  create_table "probes", force: :cascade do |t|
    t.integer "taxonomy_term_id"
  end

  create_table "processed_trait_datasets", force: :cascade do |t|
    t.integer "plant_trial_id"
    t.integer "trait_descriptor_id"
  end

  create_table "qtl", force: :cascade do |t|
    t.integer "processed_trait_dataset_id"
    t.integer "qtl_job_id"
    t.integer "linkage_group_id"
  end

  create_table "qtl_jobs", force: :cascade do |t|
  end

  create_table "restriction_enzymes", force: :cascade do |t|
  end

  create_table "submissions", force: :cascade do |t|
  end

  create_table "taxonomy_terms", force: :cascade do |t|
  end

  create_table "trait_descriptors", force: :cascade do |t|
  end

  create_table "trait_grades", force: :cascade do |t|
    t.integer "trait_descriptor_id"
  end

  create_table "trait_scores", force: :cascade do |t|
    t.integer "plant_scoring_unit_id"
    t.integer "scoring_occasion_id"
    t.integer "trait_descriptor_id"
  end

  create_table "users", force: :cascade do |t|
  end

end
```

**Comment by Nuanda** [comment]
@nowakowski Piotr, in commit f933481 I have already assumed PPL#PP_id and PPL#PL_id are required, as PPL does not make any sense otherwise.

**Comment by nowakowski** [comment]
@Nuanda Yep, this one is evident. In fact I expect most of these relations to be mandatory.

**Comment by wjurkowski** [comment]
The first chunk. 

create_table "countries", force: :cascade do |t|
  end

  create_table "design_factors", force: :cascade do |t|
	design_factors.design_factor_id -> plant_scoring_units.design_factor_id
	design_factors.institute_id -> cs_institutions.cs_institution_id
  end

  create_table "genotype_matrices", force: :cascade do |t|
  	genotype_matrices.linkage_map_id -> linkage_maps.linkage_map_id 
  end

  create_table "linkage_groups", force: :cascade do |t|
    t.integer "linkage_map_id"
	linkage_groups.linkage_group_id -> map_linkage_group_lists.linkage_group_id
  end

  create_table "linkage_maps", force: :cascade do |t|
    t.integer "plant_population_id"
	linkage_maps.linkage_map_id -> map_linkage_group_lists.linkage_map_id
	linkage_maps.mapping_population -> plant_populations.plant_population_id
  end

  create_table "map_locus_hits", force: :cascade do |t|
 	map_locus_hits.linkage_map_id -> linkage_maps.linkage_map_id
 	map_locus_hits.linkage_group_id -> map_linkage_group_lists.linkage_group_id
    t.integer "population_locus_id" 
map_locus_hits.map_position(_id) -> map_positions.map_position(_id)
  end

  create_table "map_positions", force: :cascade do |t|
    	map_positions.linkage_group_id -> linkage_groups.linkage_group_id
    t.integer "population_locus_id"
	map_positions.mapping_locus -> population_loci.mapping_locus
  end

**Comment by nowakowski** [comment]
Thanks @wjurkowski but this doesn't really answer our question - we already know which tables each foreign key links to. What we need instead is to establish, for each of the listed relations, whether it is **optional** (i.e. NULL values in key field are permitted) or **mandatory** (no NULL key values allowed).

By the way, `cs_institutions` has been dropped as per our discussion in #52 (it contained no meaningful data).

**Comment by wjurkowski** [comment]
We went through it together with Sarah and it seems that so far almost all
links with primary keys should be mandatory. Mainly because one field is a
consequence of another e.g. if there is a linkage group there must be a
linkage map as a map is higher in the hierarchy.

2015-07-07 18:15 GMT+01:00 Piotr Nowakowski <notifications@github.com>:

**Comment by teatree1212** [comment]
Is this something we can resolve?

**Comment by Nuanda** [comment]
Ok.
