### ISSUE TITLE
Definition of measurement type: investigation vs. tdf

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#315]
Wiktor - in the xls file you have sent us in May you map `i_investigation#STUDY_ASSAYS` section to BIP's trait description fields. You leave `tdf` column names not mapped to BIP model.

However, in the ISA file examples you provided us later you seem to set `i_investigation#Study Assay Measurement Type` to a generic term of `phenotyping` and then you proceed to define trait descriptors in the `tdf` file.

Which approach should we implement in the submission parser?

**Comment by wjurkowski** [comment]
This are not two opposite approaches but corresponding bits of information.  
The reason to share the first file was to show the current mapping (at least some part of it) between cropdb and the ISA. In the second one we wished to highlight general idea behind defining variables/columns to comply with the ISA format. 

So the answer is that we should use both to 1) translate/map the cropdb to naming scheme in transplant ISA 2) create new ISA-compatible variables to store remaining columns of cropdb model and oregin study
