### ISSUE TITLE
ISA files - s_study source name mapping problem

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#316]
Wiktor - in the xls file sent in May you propose to have `s_study#Source Name` mapped to plant trial's project descriptor (same value as `i_investigation#Investigation Identifier`). However, in the ISA files you sent recently, you use the `Source Name` column for other values (that seem to simply be sample ordinal numbers).

Can we simply ignore that column in the BIP submission parser?

**Comment by wjurkowski** [comment]
I can't fine 'Source Name' anywhere else than in s_study irrespectively whether its in the spreadsheet or in text file format. Could you specify what do you mean?

**Comment by Nuanda** [comment]
I didn't imply that you misplaces that column. Both in your xls tabs and in the txt tab files, the 'cource name' column appear in the s_study part.

What I meant, however, that in the xls version you suggest to map (translate, assign) it to BIP's 'plant_trials.project_descriptor' column. Yet in the ISA tab files you use this field for (a kind of) sample identifiers. Hence my question.

**Comment by wjurkowski** [comment]
This was based on a assumption that plant_trials.project_descriptor is some kind of ID of study in question. The values in ISA are just to fill it in with something for purely exemplary purpose. We could try clarify what the ID should comprise.
