### ISSUE TITLE
Plenty of problematic defaults in database model - please remove them

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#319]
Piotr, I still find a lot of DB default settings to "unspecified". I guess these are still remnants of wrong CropStore design lingering on in the current BIP model.

Please remove them all, they are of no use. If we do not require a certain field set, null value is ok. If we do require it, having a default only confuses the user who thinks the filed is not really required after all (the DB takes care of it by putting the default value in).

**Comment by Nuanda** [comment]
Committed a fix for that in #322 . Please check if all the defaults I remove are indeed not needed. In case some are useful for some purpose, please change that inside the linked PR.

**Comment by nowakowski** [comment]
@Nuanda The defaults were there to protect against null input in non-null fields. It's fine to remove them, but then the controller will have to be careful to provide a value for any field which is still declared as `null: false`. I assume you're aware of this.

Regarding relevancy, the only "meaningful" defaults in the existing model are initial counter values (which default to 0) but your migration appears to preserve these. Accordingly, I don't see anything wrong with the PR.
