### ISSUE TITLE
PPL sort_order - what is the meaning of that field

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#320]
Piotr, I need to introduce PPL as an API-accessible and API-submittable model. So I need to document its fields. Can you tell me what is the meaning of the `sort_order` filed?

Or, if it is not needed, could be simply remove that column from the model?

I also think that perhaps we do not need the annotation columns there (comments, entered_by_whom, date_entered, data_provenance, confirmed_by_whom) - after all, it is essentially just an N-to-M table...

**Comment by nowakowski** [comment]
I have to bounce this question to TGAC. The field in question appears to contain four- and five-digit values the meaning of which is unclear to me. @wjurkowski - could you comment?

I do believe that we can safely drop the remaining fields as proposed by @Nuanda

**Comment by Nuanda** [comment]
Ok, I left it as it is. It does not hurt, we simply ignore it at the moment.

**Comment by teatree1212** [comment]
Is this still an unresolved issue? I see that in the CropStore definitions, there are no descriptions on this field. Do I get that this field and annotation columns are just to be kept as is?

**Comment by Nuanda** [comment]
@teatree1212 No, I think we may rather safely leave it closed. Too many other more important things to do.
