### ISSUE TITLE
Solve setting PV countries relations by API

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#324]
There are two habtm relations between PV and Countries table. Since PV is API-writable now, please make sure there is a way for the user to set these relations.

**Comment by kammerer** [comment]
I am almost done here but one issue appeared as I changed the way relations are handled. Presently API exposes PlantPopulation#plant_line_ids in the response. Is this OK? I mean, PLs are not directly related to PPs so maybe exposing PlantPopulation#plant_population_lists_ids only would be better?

Another (minor) issue is that in the API response lists of ids are named `<plural resource>_ids`. It would slightly simplify the implementation if it was `<singular resource>_ids` (like AR methods). I am going to get rid of plurals unless you think that for some reason it is better not to do so.

**Comment by Nuanda** [comment]
I think it is ok, as long as we mark that as readonly. It's easier to traverse the model this way. BTW I have just pushed to master a small docs fix to document that PPLs_ids relation is returned.

It's ok to change it to singular_ids - it is perhaps even a correct grammar in this case :).
