### ISSUE TITLE
Figure out what's going on with the piwik outbound updates

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#326]
Mohamed claims we have some outgoing stat updates on some piwik server. Please check if one of the developers didn't add something like that.

**Comment by kammerer** [comment]
I sent two messages asking about this but received no reply whatsoever. I have not noticed anything like this myself.

**Comment by Nuanda** [comment]
Looks like some kind of misunderstanding with the TGAC admin crew. Closing for now.
