### ISSUE TITLE
Invalid models in DB after rake app:bootstrap

### ISSUE THREAD

**Issue by kammerer** [eSpectrum-IT/brassica#329]
Not sure if that is a problem, just reporting.

Magical rake task to check for invalid models: https://gist.github.com/kammerer/183dc39f80d5fb9c08dc

**Comment by kammerer** [comment]
Fixed gist link

**Comment by Nuanda** [comment]
We know this is possible. During last meeting with @wjurkowski we have decided to introduce validations for new submissions, that are not valid for older data. We assume the old CS data will not be altered via API/forms.

However I'd advise to use your test to check if we don't have unexpected things in the data.
