### ISSUE TITLE
PlantTrial submission process base

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#331]
TODOs in this issue:
 - [x] refactor submission step and content partials and forms so we have different code for different type of submission
 - [x] provide rudimentary dedicated PT submission decorator
 - [x] provide rudimentary dedicated PT submission finalizer
 - [x] refactor all PP submission specs to test PT submission process as well
 - [x] enable submission view to show PT submission tab and allow to start the PT submission process
 - [x] be able to show finalized PT submissions in both my submissions and the front page lists
 - [x] provide general PT submission description and first version of each step contextual help text.

**Comment by Nuanda** [comment]
Related branch: https://github.com/eSpectrum-IT/brassica/tree/plant_trial_submission

**Comment by Nuanda** [comment]
Switching to @kammerer for specs when all other related issues are done.

**Comment by kammerer** [comment]
PT submission request specs added in c34c0ec7dacf48266a531adc614b52f9f76f5600
