### ISSUE TITLE
PT submission: relate PT with a chosen PlantPopulation (step 1)

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#332]
Required:
 - [x] add a select field with autocomplete to pick a single PP
 - [x] require the field to be present
 - [x] relate submitted TD with the chosen PP in finalizer
 - [x] show selected PP species in the PT submission list item (first row, see decorator) both in front page and in the "my submissions" list
 - [x] show selected PP in PT submission show table (the one presented to the owner).

Related issue: #331 

Implement in branch: plant_trial_submission

 - [x] Fix 500 error or no PP for uncompleted PT submission

**Comment by Nuanda** [comment]
Doing 'save for later' on the step01 without choosing a PP first makes the submission list unpresentable (500 regarding no PP found). Please fix.

 - [ ] Fix 500 error or no PP for uncompleted PT submission

**Comment by kammerer** [comment]
> Doing 'save for later' on the step01 without choosing a PP first makes the submission list unpresentable (500 regarding no PP found). Please fix.

Fixed.
