### ISSUE TITLE
PT submission: associated TraitDescriptor list (step 2)

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#333]
Required:
 - [x] to let user choose multiple existing TDs with autocomplete
 - [x] to let user define new TDs with a form
 - [x] to create new TDs when finalizing
 - [x] to add further relevant fields to new TD form (all optional):

    t.text     "units_of_measurements"
    t.text     "where_to_score"
    t.text     "scoring_method"
    t.text     "when_to_score"
    t.text     "stage_scored"
    t.text     "precautions"
    t.text     "materials"
    t.text     "controls"
    t.text     "calibrated_against"
    t.text     "instrumentation_required"
    t.text     "likely_ambiguities"
    t.text     "score_type"
    t.text     "possible_interactions"

- [x] use combo (select or input) for trait category field
- [x] we should require at least one TD, either old or new
- [x] the current form does not let me pass to step03 when I defined my own new TD
- [x] currently I always get en empty TD name in the trait_descriptors_list.first when at step03 (regardless if I chose a TD or not in step02)
- [x] it is possible new to create multiple new TDs with the same name (we validate only against existing ones); the form itself even "hints" the old name

Related issue: #331 

Implement in branch: plant_trial_submission

**Comment by Nuanda** [comment]
*Important*! TD has no unique fields (yes, curation pending...), so when a user pick an existing TD we have to somehow remember also its ID, as otherwise it will not be possible to assign correct object in the finalizer. Also, the finalizer should not assume such an ID exists (could be deleted by then) - if it does not, it should rollback the submission to step 2.

**Comment by kammerer** [comment]
WRT "TODO FIXME Also - is this susceptible to code injection or not?" in `TraitDescriptorsController`. It is not since a prepared query is used.

**Comment by Nuanda** [comment]
On a submissions list TDs are now listed by IDs, not by names. Is this intentional? If so, I think we need to add tooltips with TD names over them.

If not, and we switch back to TD names, we still need to solve the problem of too many TD names for a single row of display.

**Comment by kammerer** [comment]
Showing IDs is a side-effect that I haven't noticed. What do you think about showing TD names in a pop-over?

**Comment by Nuanda** [comment]
If you mean a on-hover tooltip, then I agree. If a modal dialog, then I prefer to have them all listed - perhaps there will be not many traits scored in each trial.

**Comment by kammerer** [comment]
I meant a tooltip. However it looks weird if only TDs are shown in tooltip. Maybe all the details could be moved to this tooltip? It would look somewhat like metadata in datatables.

**Comment by Nuanda** [comment]
You know what, let's show all full trait descriptor names in a list - might be a bit longer for rare cases while much more informative for most cases.
