### ISSUE TITLE
Plant populations - replacing 'not applicable' PL references with NULLs

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#34]
In Plant Populations table, where male and female plant line reference reads 'not applicable', can we simply replace these values with proper DB NULL value?

This will save us inefficient sifting through data records every time we get them, in order to remove those not existing links.

**Comment by wjurkowski** [comment]
yes, and perhaps the same could be done with other symbols used to denote
empty fields

2015-03-13 11:26 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Wiktor, I know that, in general, this is what we should do. This question was actually to @nowakowski - I want to know if, given the current state of BIP model, it is already ok to do it in this particular case.

**Comment by nowakowski** [comment]
I would recommend doing away with these dummy records but only if all three (`none`, `unspecified` and `not applicable`) are semantically equivalent and can be replaced with NULLs. @wjurkowski can you confirm that this is indeed the case?

**Comment by wjurkowski** [comment]
yes lets do that

**Comment by Nuanda** [comment]
See #50 - I already remove 'not applicable', '', 'none' and 'unspecified' PLs there - so any such references will be invalid afterwards anyway.

**Comment by Nuanda** [comment]
Since #50 is merged this should no longer be an issue.
