### ISSUE TITLE
Browse data page didn't finish loading in Safari

### ISSUE THREAD

**Issue by wjurkowski** [eSpectrum-IT/brassica#356]
the progress bar is pulsing :)

**Comment by Nuanda** [comment]
What part of it? The front page. Just checked and it works rather fine here. Could that have something to do with your vpn settings?

**Comment by wjurkowski** [comment]
I hit browse_data page. The page loads completely but the progress bar is
pulsing with blue until i stop loading.

2015-07-22 9:07 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
This probably has sth to do with the export feature not working in Safari (lack of full HTML5 support in that browser :( ). There is a ticket about that and we planned to test it thoroughly and fix it after the deployment (easier testing due to not having to do with forward proxy on our side).

However, I'll try to debug it earlier.

**Comment by wjurkowski** [comment]
I confirm the same on the main and other sub pages

2015-07-22 9:20 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Can you check the same in another browser, like FF or Chrome, with your access method (which is via VPN, I presume)? That is, if the effect of unfinished loading is similar? I ask you for that since I can't access the service the way you do.

**Comment by wjurkowski** [comment]
I tested chrome, no problems with it

2015-07-22 9:24 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Fixed.

**Comment by wjurkowski** [comment]
Thanks! At the same time we finally got the certificate. BIP is online!

2015-07-22 11:16 GMT+01:00 Tomasz Gubała <notifications@github.com>:
