### ISSUE TITLE
Do not require things like comments, description, data_provenance

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#36]
I know the original CS author always required values for these fields, and then supplied some placeholder like 'unspecified' if the user did not provide any value.

However, it is probably much better to not require these values in the first place and allow NULLs in the database.

**Comment by nowakowski** [comment]
This is a general concern affecting the entire database - as you will see in the bootstrap migration, nearly all fields have NOT NULL constraints defined. I believe that placeholder defaults (such as "unknown" or "unspecified") could be a reasonable compromise between dropping all these constraints and having to supply meaningful value for each field when inserting a record. I would welcome @wjurkowski input here - is it OK to insert records with NULLs or would you rather prefer placeholders whenever a specific value is not provided?

**Comment by kammerer** [comment]
I am for allowing NULLs as placeholders in the DB do not add any value.

**Comment by Nuanda** [comment]
Why do we wait 26 days to solve sth so simple like that? This might not look so, but this is a serious problem to all controller/view layers of the system, since those layers have to _force_ other subsystems (or the user!) to provide placeholder values for fields we do not need/we should not require.

And all that code will be immediately thrown away after we solve this issue. Please treat this as a top priority.
