### ISSUE TITLE
IE10 glitches

### ISSUE THREAD

**Issue by kammerer** [eSpectrum-IT/brassica#366]
- [ ] Page size select looks strange
- [x] Duplicated clear icon in combo text input

![screenshot from 2015-07-24 10 25 34](https://cloud.githubusercontent.com/assets/14025/8872250/a6ca615a-31fb-11e5-9ad1-33804e3738ea.png)

![screenshot from 2015-07-24 11 32 29](https://cloud.githubusercontent.com/assets/14025/8872291/e69eb33a-31fb-11e5-8e94-6132c391a7e0.png)

**Comment by Nuanda** [comment]
I spotted the first thing a while ago but I don't consider it a problem - as long as the selection functionality works.

The second thing would be nice to fix, though.

**Comment by kammerer** [comment]
Fixed duplicated clear icon in fa78de3a419d4d9293de75cff22f6270c14fb20c. It appears that clear icon is a feature of IE, fortunately it can be disabled.

**Comment by Nuanda** [comment]
Deployed changes made so far, you can re-check it now.
