### ISSUE TITLE
Broken country names

### ISSUE THREAD

**Issue by kammerer** [eSpectrum-IT/brassica#367]
![screenshot from 2015-07-24 11 43 23](https://cloud.githubusercontent.com/assets/14025/8872353/782e0e72-31fc-11e5-8b45-fde8ecc4e48a.png)

**Comment by Nuanda** [comment]
Isn't it initial CS data coding problem? I saw similar coding things in some varieties names.

**Comment by kammerer** [comment]
You are probably right, still this is sth pretty easy to fix.

**Comment by Nuanda** [comment]
@nowakowski Piotr, are you able to curate that table content?

**Comment by nowakowski** [comment]
On it.
