### ISSUE TITLE
Wrong uniqueness index in the PPL joining table

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#37]
The current migration says:

     create_table "plant_population_lists", primary_key: "plant_population_id", force: :cascade do |t|
        t.text "plant_line_name",   default: "unspecified", null: false

I believe this is wrong, it prevents assigning two different PLs to the same PP.

**Comment by Nuanda** [comment]
I think it's even worse :(. There are TWO migrations creating that table - both probably equally wrong.

**Comment by nowakowski** [comment]
Yes, this duplication is strange. Fixed.
