### ISSUE TITLE
Ask admins to snapshot the entire BIP VM once

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#378]
Wiktor, this is rather important. And we don't have sufficient access rights to do that on our own.

Please ask the TGAC administrators (probably by filing a new request in their tracker) to snapshot the current BIP VM machine. This will produce a snapshot vm image which they should store in a secure place they have easy access to. The purpose is the following.

Once a Big Disaster (TM) comes, which physically switches off/ruins the server, so there is no possibility to recover and even access the broken instance of BIP, we need to setup a new BIP server. Having to do that from a bare operating system installation takes hours, while creating such a server from a ready vm image file takes minutes (all packages, libraries, servers, configurations and application code is already there).

It is enough to do the server snapshot once, since we assume anyway that the user data will be recreated from daily backups (which is another issue altogether).

**Comment by wjurkowski** [comment]
request submitted

**Comment by wjurkowski** [comment]
Response:

1) Every night a snapshot of all VM's is taken using VMWare VSC (Virtual Storage Console). These snapshots are retained for 8 days.

2) Every night all VM's get a backup by our central backup software Simpana. These backups are held on separate storage and retained for 30 days.
