### ISSUE TITLE
Add team members names and affiliations to the about us page

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#380]
Write the first version, get @wjurkowski acceptance/input, implement.

**Comment by Nuanda** [comment]
Brassica Information Portal Team

  * [Sarah Ayling](http://www.tgac.ac.uk/bioinformatics/computational-genomics/sarah-ayling/), the leader of the Computational Genomics Group at TGAC, UK, who serves as the head of the BIP project,
  * [Wiktor Jurkowski](http://www.tgac.ac.uk/science-faculty/integrative-genomics/), the leader or the Integrative Genomics Group at TGAC, UK, who is the main consultant for the BIP,
  * Tomasz Gubała, Tomasz Szymczyszyn and Piotr Nowakowski, from [Spectrum IT](http://espectrum.pl/it), who designed, implemented and deployed the service.

**Comment by Nuanda** [comment]
@wjurkowski Wiktor, is this more or less what I should put there (see the comment above)?

**Comment by wjurkowski** [comment]
- Sarah Ayling
   <http://www.tgac.ac.uk/bioinformatics/computational-genomics/sarah-ayling/>,
   Computational Genomics Group, TGAC
   - Wiktor Jurkowski
   <http://www.tgac.ac.uk/science-faculty/integrative-genomics/>,
   Integrative Genomics Group, TGAC
   - Tomasz Gubała, Spectrum IT <http://espectrum.pl/it>
   - Tomasz Szymczyszyn, Spectrum IT <http://espectrum.pl/it>
   - Piotr Nowakowski, Spectrum IT <http://espectrum.pl/it>

Perhaps we should also add the link to software repository (after it is
migrated) in the contact us section

Also in About please add:

BIP source code is available at: 'link'
Please get in touch with ideas and patches to further improve it, we are
always happy to accept new contributors.




2015-09-17 8:50 GMT+01:00 Tomasz Gubała <notifications@github.com>:
