### ISSUE TITLE
Add published flag column to all user-writable tables

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#383]
VERY IMPORTANT: add a spec that tests if there are no tables which could be populated by user, either via the submission system, or via API, and that do not have the new published flag.

Default all current data to published, not private.

*OR* add the flag field to *ALL* tables (which makes the spec mentioned above not required). This might be more practical option.

**Comment by Nuanda** [comment]
I'd like to reopen this issue, for two reasons.

First, I think we may drop that new flag for submission_uploads, since they are always related to submissions (logically more than related - they are "part of").

Then, we should perhaps rename the published flag for submissions. Technically it will have different semantics, compared to the "core" Brassica/CS classes. It will decide:

- (a) whether a finished submission appears in the front page latest submissions list (issue #429), and
- (b) if all objects created during submission finalization will get published flag set to true or false (see issue #387).

So, maybe, a slightly different flag name would be appropriate to reflect that different semantics.

@nowakowski @kammerer Can we do that?

**Comment by kammerer** [comment]
Agreed that we can remove the flag from submission_uploads.

As for the different semantics - it looks quite closely related to me. I mean the submission's flag should be consistent with the flags for objects spawned by this submission (at least until the latter ones are explicitly altered as in  #386). The fact that submission is not a "core" class justifies the difference IMHO.

However, there is other issue - so far we used `#published?` method to check if objects created via API can be destroyed. We'll probably need to replace it with other method taking into account both the boolean flag and currently checked condition.

**Comment by nowakowski** [comment]
Of course dropping `SubmissionUploads.published` is not a problem; I'll take care of it.

It seems to me that @Nuanda is actually asking for two distinct features:
  - Is this submission complete and ready to go live?
  - Will this submission's objects be set to "published" once the submission goes live?

From the perspective of the data model this calls for two separate flags (e.g. `finalized` and `public` respectively). Note that I would not name either flag `published` to avoid confusion (different semantics -> different attribute name). Assuming that I have correctly interpreted @Nuanda 's request , that's the way I would propose to do it.

Regarding `#published?` - @kammerer is right in that there is a naming conflict here. From what I can see, the current condition is `updated_at < Time.now - 1.week`. Frankly, I do not understand the logic here - there seem to be some hidden assumptions at play. Why are we only allowed to destroy objects that are at least 1 week old? What's the origin of this "magic variable"?

**Comment by Nuanda** [comment]
1. @nowakowski So, please remove the published flag from SubmissionUploads.

2. @nowakowski One flag is enough as this should be consistent - giving two flags makes contradictory situation possible (submission is public but its data is not). So let's have a single flag - "public" is ok, if nothing else comes to mind :).

3. @kammerer I forgot about the previous #published? method - Wiktor asked us to have a one week "grace period" (at that time he had a plan of a kind of manual "supervision" of submissions). I guess we will no longer need that - so it might be safe to re-purpose #published? for the new role. Can I ask you to look around and see where the old #published? method is being used? I know the metadata popup in the datatables uses that (but only to inform the user). Does delete API uses that as well? In the meantime I'll ask Wiktor if that 1 week period is still necessary.

**Comment by kammerer** [comment]
2. I'd rather not use `public` for a method name.
3. It is used to check if an object can be deleted via API.

**Comment by nowakowski** [comment]
`publishable` then?

**Comment by kammerer** [comment]
Ok

2016-03-16 10:56 GMT+01:00 Piotr Nowakowski <notifications@github.com>:

> publishable then?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/383#issuecomment-197236077>
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
In case we still need the older #published? are we going to rename the new flag?

**Comment by kammerer** [comment]
I'd rather rename the old method and leave the new flag as is.

2016-03-16 11:03 GMT+01:00 Tomasz Gubała <notifications@github.com>:

> In case we still need the older #published? are we going to rename the new
> flag?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/383#issuecomment-197239616>
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
I'll tell you when Wiktor writes me an answer. In the meantime @nowakowski can freely go with submission and submission_uploads changes.

@nowakowski Going back to the original issue description (see the top of this page). Since we are not adding the new flag to all models, can you please provide a spec that tests that the new flag exists in ALL tables EXCEPT the ones we deliberately excluded? This way, in the future, we will not add a new "core" table and forget about that flag.

**Comment by Nuanda** [comment]
For the record: we have decided to have two new fields for each model - "published" (boolean) and "published_on" (datetime). The semantics is as follows:
1. when no `user_id`: it is always public, not removable (alterable), no one can make it private, no flags are important
2. otherwise:
- when `'published' == false`: it is not public, owner can remove/alter it, owner can publish it
- otherwise:
 - when `'published_on' == nil`: internal data inconsistency; should never happen ;)
 - when `'published_on' > Time.now - 1.week`: it is public; not removable/alterable (right now) but it can be made private again
 - otherwise: it is public; no longer removable/alterable (so-called "quotable" data).

Also, @nowakowski decided not to add these new flags to `plant_variety_country_of_origin` and `plant_variety_country_registered`.

**Comment by Nuanda** [comment]
I realized now that the new flags (published, published_on) do not make much sense for models, where we do not have user_id (see the algorithm below) - so I asked @nowakowski to remove them. After we merge #433 work may proceed in #384 #389 #390. Other issues I set "on hold" - I will update them when I further discuss that with @wjurkowski.
