### ISSUE TITLE
Make all Browse section tables privacy-aware

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#384]
This is a complex task - all datatables in the Browse section, in general case, should show only published data (if data ownership is not established - i.e. the user_id column is NULL, treat data as public).

For logged in users, the tables should also show private data (that is: **all owned data**, regardless the published flag value, and all **other data that is published**).

Please keep the generic model query mechanism established so far - since the problem at hand is generic for all tables, it should be doable to treat it that way in code as well.

Also consider joints - what happens in a view table, that draws a single column values from another database table, when the privacy settings differ.

**Comment by Nuanda** [comment]
@nowakowski Piotr, any progress with this? This is our priority now so let me know if there are any obstacles or problems.

**Comment by nowakowski** [comment]
It's in progress - cf. https://github.com/eSpectrum-IT/brassica/tree/privacy_aware_browsing
I got sidetracked by other issues lately but I will continue to work on it over the coming 2 days.

**Comment by Nuanda** [comment]
@nowakowski Is this solved by recent PRs or something is still missing?

**Comment by nowakowski** [comment]
Yes, this issue is addressed by #460 which has already been merged into master. Closing.
