### ISSUE TITLE
Extend API with published flag

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#388]
Since the DB tables and the model are going to be extended with the published flag, the API should automatically both show and set that flag, when querying/creating data. Just make sure it works that way.

Extend the API docs by the description of that concept.

**Comment by Nuanda** [comment]
Also, please do test if one cannot retrieve someone else's datasets through GET API, when those datasets are marked _private_.

**Comment by Nuanda** [comment]
Currently API force-sets all submitted data to published, with published_on set to Date.today.

**Comment by Nuanda** [comment]
@kammerer Tomasz, do you think we are able to start that? I think to make the following changes:
 - let the user to set published to false when submitting new data
 - never let the user to set published_on (as it is now)
 - add another API calls ("publish"/"revoke") that would set the published flag of referenced resources to appropriate value (and updating published_on for "publish"); that API call will need to check resource's ownership (for both operations) and the revocation period (for "revoke").

Is this reasonable? Any additional issues I forgot?

**Comment by kammerer** [comment]
Make sense. I do not see any more issues right now.

**Comment by Nuanda** [comment]
All right. Please proceed with this task, as the next assignment.
