### ISSUE TITLE
Provide the final version of the RIPR trait data

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#391]
Especially take care to fix the cultivar names and get the full trait descriptor names. In case these traits are not present in the BIP's trait list at the moment, it would be useful to get more data about these traits - see https://bip.tgac.ac.uk/api_documentation#trait-descriptor for additional information that may be stored in BIP for a trait descriptor.

**Comment by teatree1212** [comment]
The cultivar names and trait names should have been submitted to you by now.

**Comment by Nuanda** [comment]
@teatree1212 Simply to have all these links in the GH as well, the final file with trait names is this one:

https://docs.google.com/spreadsheets/d/1VNq_BbZ8ieW8e-rjrTA5C7OcfpTcA3hOyNtZITu9TxM/edit#gid=1514310994

?

**Comment by teatree1212** [comment]
for the traits ( first document) Columns HIJK may be the most interesting for you. Consider columns A-F Synonyms of the trait to be importet (col I ). If the synonyms can be captured somehow, maybe as comma separated list of names in a trait_synonym column that would be great. It doesn't need to be displayed if not possible.

**Comment by Nuanda** [comment]
@teatree1212 I have some questions related to the curated Trait list, but I'll move them to #420 as it is a more suitable place for that.

**Comment by Nuanda** [comment]
Trait data prepared by Annemarie loaded to BIP. Closing.
