### ISSUE TITLE
Add Plant Accession table to available datatables in the Browse section

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#395]
If too congested, consult TGAC about which columns should be shown.

**Comment by Nuanda** [comment]
@teatree1212 Annemarie, you are able to see the PlantAccession table here:

https://bip.tgac.ac.uk/data_tables?model=plant_accessions

Tell me, what columns should I remove and what other columns should I add there to make the table more useful to users?

The current column list for that table is as follows (excluding those used in the Metadata popup):

```
    t.text     "plant_accession"
    t.text     "plant_accession_derivation"
    t.text     "accession_originator"
    t.text     "originating_organisation"
    t.text     "year_produced"
    t.date     "date_harvested"
    t.text     "female_parent_plant_id"
    t.text     "male_parent_plant_id"
    t.text     "confirmed_by_whom"
    t.integer  "plant_line_id"
```

**Comment by teatree1212** [comment]
I am not sure what the accession originator is good for. the Organisation is definitely important. I will ask someone..
