### ISSUE TITLE
Decide which Trait Descriptor columns should be mandatory

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#406]
It was suggested the trait scoring method is one such field. Are there others? Please provide a list (also, for other models, if you feel something more should be required).

The quality of being mandatory holds for both manual and API submissions.

**Comment by teatree1212** [comment]
we were thinking of making the submission of a methods text  for the  measurement of a trait compulsory. How could we attach that to a Score?

**Comment by Nuanda** [comment]
@teatree1212 During the 2nd step of the submission, when you define a new Trait Descriptor, you can supply scoring-related information, including _Scoring method_. As you know, all information related to the method and the process of scoring a particular trait, is included in this table (trait_descriptors). We can make that field of the new TD form mandatory - we can also force users to submit that information when creating new TDs through API.

So the users do not attach any scoring method information to the scores themselves (the 3rd step). But also keep in mind the ongoing email discussion about what we are going to do with TD (re. plant parts, trait ontology, scoring process description etc.). Perhaps we should wait with this issue until we solve that other thing first.

**Comment by teatree1212** [comment]
#488 should answer this

**Comment by Nuanda** [comment]
You are right. Closing this one.
