### ISSUE TITLE
Providing content for better explanation messages (context help) for submissions

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#407]
It was suggested that the current submission steps should be outfitted with better help messages, more explanations, examples etc. Please provide these text messages so we may put them in the right place inside the submission processes.

**Comment by teatree1212** [comment]
This is just for the Plant Scoring trial submission so far. The text in () is just messages to whoever inserts the texts on the website.

**Trial information:**


Plant scoring trial:
Please, provide convenient name for this scoring trial. It has to be unique. 
Example: <research institution acronym>_<trial year>_<TrialPlotLocation>_<if needed:counter>
This is an example of an existing trial entry in the BIP: hzau_2003_Weinan_01


Please provide the name of the project the trial is part of.
Examples of existing project names in the database are:  OREGIN, RIPR, IMSORB


(corrected spelling mistake in bold)
If the trial was performed for a population that is not listed in BIP, **please** use Plant Population submission to upload information about that population first.


Trial description
Please provide a brief description of the trial. It should contain the trait and population of interest, the trial type and -location. The Project number could be named, too.
An Example of an existing trial description in the data base is: "Seed quality assessment of the BnaTNDH population in a field trial in China"


(please confirm the part in italics)
Trial year
Please provide information on the year the trial took place. _Note that you can only submit trait data from one year at a time_
Examples of years in the database are: 2004, 2005, 2016

Place name
Please provide a geographical name of the trial Location, such a s a town 

Trial location site name
Please provide the name of the field, glasshouse or growth room used for the trial.
Examples of place names in the database are: 'Wharf Ground' or 'unspecified glasshouse in Wellesbourne'

**Traits:**

Traits.
Before uploading your trait score sheet, please choose plant traits that were scored in the course of this trial, or define new trait descriptors. Further instructions are found below.
Examples of plant traits in the database are: 'oleic acid content'   or ' seed mature time'

(note that trait names may be subject to change)

**Scoring**

Scoring.
Please upload a tabular list of scores given to plants pear each trait scored. Further instructions are found below.


-----------------
besides, depending on the extension of the wizard trial submission, more fields would need to be described and the spreadsheet submission description changed of course.


In step 2, besides selecting a trait, a corresponding unit should somehow be selected as well for now. I think it is easier to add the unit here than to add it in the spreadsheet.

In step 2, a description of the data would need to be included with something like

Calculation status.
Please provide information on the nature of your data.

Raw 
Mean
if yes > arithmetric mean, harmonic mean, geometric mean


in step 3 the way  I imagine the changes, the resulting instructions could be re-written, including some pictures I suppose as follows:

in case of raw data:
Please upload the file with your trait score values. The required format is simple and features several compulsory fields named in the order required: 
column 1 line or cultivar name, 
column 2  Accession name 
column 3 plot
column 4 replicate
column 5- 100 trait names in the order and spelling specified in step 3.

One column following traits can contain any additional information or id for your internal laboratory purposes. Please name it with an appropriate name. It will only be accessible to you.

in case of mean data:
in case of raw data:
Please upload the file with your trait score values. The required format is simple and features several compulsory fields named in the order required: 
column 1 line or cultivar name, 
column 2  Accession name 
column 5- 100 trait names in the order and spelling specified in step 3.

----------------

**Comment by teatree1212** [comment]
Population submission

again, as there should be improvements in the Population submission, this is not entirely valid.
**
basic Information**

Basic information.
Please provide a unique name and a description of your population.

Population name
Please, provide a population name.
Examples of a population name in the database include: BnaTNDH, BolEC03.

Description
Please provide a brief description of the Population. This is a description of the TNDH population, taken from [here](https://www.jic.ac.uk/staff/ian-bancroft/mapping.html):
'The TNDH mapping population was developed by Prof. Jinling Meng, at the Huazhong Agricultural University, Wuhan, China in collaboration with Prof. Ian Bancroft at JIC as part of the EU-funded IMSORB project.
This population is derived from an F1 cross between Tapidor, a European Winter B. napus variety, and Ningyou7, a Chinese semi-Winter B. napus line. These parents were selected on the basis of their genetic dissimilarity, being the most divergent lines identified using RFLP markers (Meng et al., 1996) and for their contrasting trait characteristics and cultivation ranges. '

Population owned by
Please provide information on who owns the population. For example, the name(s) of its developer(s).

**Population type.**

 Population type.
Please, choose the type of population you are submitting.

( as taxonomy term and population type can be selected, they are rather self-explanatory and no further explanation and examples are needed)

**Plant lines.
**
Plant lines.
If applicable, please pick parent lines and define the list of plant lines connected with the submitted population.

( and I think the rest of the Plant lines section needs restructuring the submission at some point, but I have to hear back from some experimentalists about my thoughts)

**Provenance.**

Provenance. 
Please identify the owner of the submitted data and describe its provenance.

Data owned by
Please provide information on the owner of the data. For example, it can be a submitter, a research groupe, an institute or the project. Ideally, please provide an email address, too.

Data provenance
If the current owner and the original owner differ, please provide information on the original owner of the data. 

Comments
If there are any more comments on the population or the data ownership you would like to make, please enter them here.

**Comment by teatree1212** [comment]
I take back suggesting column 2 Accession name as a compulsory column.

**Comment by Nuanda** [comment]
All suggestions, apart from Trial submission step 3, done in #506.
