### ISSUE TITLE
Faster inter-submission process navigation

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#409]
Make the circular "metro line station" markers clickable so a user may quickly go back >1 step in the submission process. She should also be able to go forth >1 step as long as no unsubmitted step is overlooked.

**Comment by kammerer** [comment]
@Nuanda I am not sure what to do if user made some changes before going to desired state. I see three options:
1. Discard the changes (same as the "Back" button) - in a way makes sense but probably not the best UX 
2. Save the changes - IMO worse than the first option
3. Try to detect changes and ask if these should be saved or discarded - probably best UX but obviously more work involved

**Comment by Nuanda** [comment]
I think it should be consistent with the functionality of the Back button. A question before we go ahead - when I add a Trait Descriptor, and I forget to Confirm the new TD form, before I go ahead with the wizard, I think I lose the data. Could the changes detection feature, you mention in the 3rd bullet, be used also in this case, to warn the user before going ahead and losing all input?
