### ISSUE TITLE
Provide curated Plant Ontology document to be imported to BIP

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#412]
This will extend the current Plant Part table. If possible it would be great to have it in the OBO format.

**Comment by teatree1212** [comment]
creating a brassica-specific crop ontology will still take until end of July currently we suggest using the Trait ontology and plant ontology. 
https://raw.githubusercontent.com/Planteome/plant-trait-ontology/master/to.obo
https://raw.githubusercontent.com/Planteome/plant-ontology/master/po.obo

**Comment by Nuanda** [comment]
Currently, we have 6 PlantParts in our data (each of them already used for at least 1 PlantTrial), that we should map to PO terms:
 - "whole plant" -> probably PO:0000003
 - "pp.EarlyLeaves_01" -> maybe PO:0025034 (leaf) or one of "leaf stages" (start with PO:0001050 and further)?
 - "pp.CanopyLeaves_01" -> ?
 - "whole plot", "average of blocks", "average of trays" - aren't those rather trait scoring computation strategies (i.e. the method how the final score value is being calculated)?

Anyway, it looks like more questions for you :). Perhaps also a data curation issue.

**Comment by Nuanda** [comment]
Also - another question - which PO namespace(s) should we import to the PlantParts table? `plant_anatomy` seems obvious. What about `plant_structure_development_stage`?

**Comment by teatree1212** [comment]
you are bumping into the same issues as I did here. I contacted the PO people by raising an issue   [here ](https://github.com/Planteome/plant-ontology/issues/628) but no response.
I think, for now, just  define the Canopy and early leaf as a leaf. I had a look at the "vascular leaf development stages" (PO:0025570) and they are not suitable for our database, as they all happen on a molecular level uninteresting and not discernable for field experimentalists.

Yes, Whole Plots etc should not be there. can you show me an example in BIP where this is the case?

**Comment by Nuanda** [comment]
For instance: https://bip.tgac.ac.uk/data_tables?model=plant_scoring_units&query[plant_trials.id]=2 (average of blocks). Together with "Units scored",  "Sample size" and "Frame size" it looks to me like one of those "mean data" trial submissions. Would you be able to curate such cases?

**Comment by teatree1212** [comment]
This is a curation issue for later. Plant part should be a trait term, in this case the whole plant. The average of blocks should be part of the experimental design, maybe in the design factors table. or even just in the trait descriptor "materials and methods" column.

**Comment by Nuanda** [comment]
Closing this and moving the remaining curation issue for #530
