### ISSUE TITLE
Decide on what level the plant part should be referenced

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#416]
Currently, each Plant Scoring Unit relates to a Plant Part. We may keep that - in such a case, the 3rd step of the Plant Trial submission - where the user uploads the Trait Scores data - will be extended with additional column to reference the correct Plant Part.

*Otherwise* we may move this relation away from PSUs to the level of Trait Descriptors - i.e. have each Trait Descriptor relate to a single Plant Part (and have similar traits that could be scored on different plant part split into multiple Trait Descriptor records). Then, the choice of adequate Plant Part will be done in the 2nd step of the submission, if the user decides to create new Trait Descriptors.

This decision also impacts API accordingly.

**Comment by teatree1212** [comment]
We think that we need to keep both (change 'Otherwise' to 'In addition' in your description). The reason is to 1) be able to search for PSU related to specific plant parts; 2) This is the right thing to develop the TO further to make all terms plant part specific

**Comment by Nuanda** [comment]
Well, but what is the domain explanation for this? If, as you suggest, I have a TraitDescriptor that has a relation to PlantPart::Leaf, and there is a PlantScoringUnit for this Trait, that has relation to PlantPart::Stem, how should I interpret that? That: "This trait should be normally scored on a leaf but in this particular case, of this particular plant, it was scored on a stem"?

**Comment by wjurkowski** [comment]
This shouldn't normally happen. It might happen that the trait is generic enough to be applied to any plan part, but if TO term includes plant part (as it is in some cases and what will eventually happen when the trait ontology will grow) then it should only be used in measurements on that plant part. e.g. use of hypothetical TO term 'nitrogen_uptake_third_leaf' to describe measurement of N in a plant stem would be incorrect, an inapprioriate description in the input data set that would require curation before the upload. Lets leave the correct upload preparation to the user. This will be a complex process to on one hand  enrich TO with more informative terms and on the other educate user base to use these terms in headers of data collection spreadsheets.

**Comment by Nuanda** [comment]
@wjurkowski Wiktor, if I get it correctly, you propose to (see the original posting in this thread) actually move the PlantPart relation, away from the individual PSU level, to the TraitDescriptor level, and assume, that all scorings of this particular Trait are taken using the PlantPart mentioned in the TraitDescriptor?

**Comment by teatree1212** [comment]
To finish this off, I think most of us tend towards relating the PlantPart directly to the TraitDescriptor. This means that the submission of Plant part needs to be made part of the 2nd submission step.

**Comment by Nuanda** [comment]
Ok. There is still the question of strange values and what to do with them, see #412
