### ISSUE TITLE
Decide what table will serve as the "trait dictionary" for BIP

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#419]
This is in the context of the Trait Ontology being imported into BIP. Decide if we are going to import the curated TO into the Trait Descriptors table (trying to provide also all the other data that is expected there, like scoring methods, equipment and so on), or if we provide a separate table for that.

In the second case, a new table will serve as the trait dictionary. It's structure and role will similar to the Taxonomy Term table. It will store names and (possibly) Planteome identifiers for all Trait. The current Trait Descriptor table will lose its "name" column and will get a relation to the new "dictionary" table, instead.

**Comment by teatree1212** [comment]
#505 traitDescriptor table should include (an) additional column (s) including  TraitOntology and  if applicable CropOntology terms our database maps with.

**Comment by Nuanda** [comment]
We are going to have a separate "vocabulary" table, called simply Trait, that will hold all non-obsolete TO trait names, all current CropStore TraitDescriptor.descriptor_name values and, in the future, perhaps also other project's trait names (curated by @teatree1212) and also CO trait names, if we are able to conciliate the CS/TO model with the CO model.
