### ISSUE TITLE
Encoding problems with trait scoring file submission

### ISSUE THREAD

**Issue by teatree1212** [eSpectrum-IT/brassica#438]
I am unable to upload this file using the wizard: 
https://drive.google.com/file/d/0B1POnvEDtIbINGxXQXRORE9ZOFk/view?usp=sharing
getting the following parsing message:
https://drive.google.com/open?id=0B1POnvEDtIbIRXMxYVZLa0ZKQUk

**Comment by Nuanda** [comment]
@teatree1212 Can you send me the file you try to upload directly via an email? This issue is about strange UTF encoding and google docs may change that (I think) - it is better to have the original file for testing.

**Comment by teatree1212** [comment]
sent the document via email to Tomasz.

**Comment by Nuanda** [comment]
New task: detect encoded files and inform the user about that. Also we will want to replace TSV with CSV as the latter is less problematic for users.
