### ISSUE TITLE
Rename and refactor #publishable? method

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#441]
We need a new name for that, and we need it to work slightly differently. Its purpose is the following:
 - it says if the owner of data is able to set it from public to private
 - as a consequence, it says if the owner of data is able to API-delete it
 - it tells the other users if data is "quotable" (if it no longer can be made private/deleted) - this information is given inside the Metadata popup in the rightmost column in the datatables.

It should span 1 week from the published_on date.

**Comment by kammerer** [comment]
@Nuanda I am not sure if I understand. Right now there is a Submission#publishable? method in PN's  remove_published_from_submissions branch, but you are not referring to it, are you? It wouldn't make sense in the context of API-delete, since API-created objects are not related to a Submission object.

So, are you telling me to add a new method (say, #revocable?) to every class which will have the #published? method?

**Comment by Nuanda** [comment]
What I meant the old (pre-extension) method that blocked deleting data older than a certain period of time (a week). Since we use 'published' for something else now, but that old method is still needed (albeit, as I have written, with a slightly changed semantics), we need to do the refactoring.

**Comment by Nuanda** [comment]
@kammerer Tell me if this is clear now? We need to solve this as a priority, before going any further with data privacy management.

**Comment by kammerer** [comment]
Yes, I was confused since the method to refactor is called #published? but
it should have been obvious anyway.

2016-03-24 9:24 GMT+01:00 Tomasz Gubała <notifications@github.com>:

> @kammerer <https://github.com/kammerer> Tell me if this is clear now? We
> need to solve this as a priority, before going any further with data
> privacy management.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/441#issuecomment-200730902>
>



-- 
Tomasz Szymczyszyn
