### ISSUE TITLE
Switch user data upload from TSV to CSV

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#442]
A proposition. We use CSV format for data download, yet we happened to set TSV format for data upload (in the Plant Trial submission). Perhaps we should switch to CSV data upload?

One thing I dislike about TSVs is that many editors deliberately change tabs to spaces (tabs in source code is the root of all evil, as we well know ;)) - no such problem with CSVs. While we (and users) use dots as fraction separators, there should be no problem with numerical data in CSVs, right?

@wjurkowski @teatree1212 what do you think?

**Comment by teatree1212** [comment]
I think this is a good idea.

**Comment by Nuanda** [comment]
@wjurkowski Wiktor, what's your opinion?

**Comment by wjurkowski** [comment]
Agreed

**Comment by Nuanda** [comment]
Blocked by: #481
