### ISSUE TITLE
Change BIP statistics for now- Population subsets in PlantTrial

### ISSUE THREAD

**Issue by teatree1212** [eSpectrum-IT/brassica#444]
Hide BIP statistics for now:
We have noticed that the BIP statistics states that there are 150+ Plant Populations in the Database. This is most likely not true. The Trials in the Database usually use their material from similar populations like the "TN" population, which is a product of the cross of Tapidor and Niguou 7( or sth like that). Therefore, please remove the statistics for now, as in early April we will encourage the Brassica Community to visit the website and give feedback.

This however needs to be further investigated and I have the following thoughts/ explanations about the issue

Population subsets in Plant Trial:
All Trials using lines from this cross just draw their  genetic material from this crossing event. However, it is important to somehow distinguish between the Trials using different subsets of this population, as they derive the linkage maps from just this subset. I wonder whether this  could be captured in a Population_Subset  identifier, which then gets linked to the respective map/ qtls.

**Comment by Nuanda** [comment]
I just checked and there really is 152 Plant Populations in the system - so the statistics is true. Although, I understand, that you think it is somehow misleading for the users, who have a different semantics of the term "plant population" in their minds, right?

**Comment by teatree1212** [comment]
yes, the definition of a population is that is either derived by crossing two cultivars or lines( genetically quite different individuals), by mutagenesis (TILLING) or a diversity set ( a set of many cultivars that have very different traits). - t_his is also why it is so hard to keep up with the definition of a *line* in the database, as for example the RIPR project uses a lot of cultivars rather than lines, but not exclusively cultivars, but this is another topic_-

I see what you mean. But again, they draw their lines from the same populations=> Have a look at the names of the populations: they are called for example: BnaDYDH_01 to BnaDYDH_05.. which means that actually, the the **b**rassica **na**pus cross of **D**armor  and **Y**udal  population with the genetic status being **d**oubled **h**aploid, has generated a lot of lines, which are then being further investigated by trait scoring and qtl analysis and subsequently mapping the traits onto the chromosomes.  After generating this population they only used a subset of these lines for further experiments, but still called them *population* to refer back to the population the lines are part of.
e.g.
BnaDYDH_05 is linked with map 	BnaDYDH_05_2010a
BnaDYDH_03 is linked with map    BnaDSDH_00_2001a

**Comment by Nuanda** [comment]
I think I understand. But perhaps we could think of another statistics there, that might be interesting to the user - maybe the number of Plant Trials that we store?

**Comment by teatree1212** [comment]
I agree-yes, statistics are generally a good thing. if that is a sensible number,I think that is a good alternative.
