### ISSUE TITLE
Show uploaded and confirmed trait scores information in step 3

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#452]
Maybe I misunderstand something there but I think Plant Trial submission's step 3 does not show uploaded _and confirmed_ trait scores, when you do NEXT and BACK again. In other words, the finalization will create scores but the third step form suggests it will not.

Please confirm and, if i'm right, try to detect that situation and provide a suitable information.

**Comment by Nuanda** [comment]
@kammerer Tomasz, does #479 do anything regarding this issue? Or, can you confirm the problem described here?

**Comment by kammerer** [comment]
#479 does not affect this in any way. I don't remember now how it was supposed to work originally but showing trait scores seem to be a good idea.

**Comment by kammerer** [comment]
@Nuanda 
It seems that it works as expected (as originally implemented) - no scores are shown, only the parsing summary. It is shown after uploading file as well as when going to next step and then coming back.

Do you want me to add a table with actual scoring values?

**Comment by Nuanda** [comment]
Let's put that on hold for a time.
