### ISSUE TITLE
Consider a non-flash fallback for csv export button

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#46]

**Comment by kammerer** [comment]
@Nuanda I initially thought about server-side solution but it seems HTML5 File API is so widely available that it may be a good alternative.

http://caniuse.com/#search=file%20api

**Comment by Nuanda** [comment]
http://datatables.net/forums/discussion/7583/need-tabletools-export-functionality-to-work-without-flash

**Comment by Nuanda** [comment]
Used resources:
 - https://github.com/DataTables/TableTools/blob/master/js/dataTables.tableTools.js
 - https://github.com/mholt/PapaParse/issues/175

**Comment by Nuanda** [comment]
See also #267
