### ISSUE TITLE
Retrieving all current plant_variety names using API

### ISSUE THREAD

**Issue by teatree1212** [eSpectrum-IT/brassica#470]
How can I query for all possible variety names using the API?

**Comment by Nuanda** [comment]
Is a ruby script that you run locally ok for you?

**Comment by Nuanda** [comment]
@teatree1212 Perhaps I wasn't clear with my remark :). I mean - if I prepare a script in a ruby language, that you could be able to run with the command line ("ruby script.rb") and it will print CSValues to your console - would that be ok for you (you can redirect it then to a file)?

You see - API stands for Application *Programming* Interface, and it is really intended to be used from a programming tool (like, for instance, a scripting language).

**Comment by wjurkowski** [comment]
yes, running a script is what we expect :). What Annemarie meant is an example of script to do the job (get all possible variety names - to let user know what they can find in the db)

**Comment by Nuanda** [comment]
@teatree1212 Annemarie, here's the recipe:
1. Get your private API key (login to BIP, click you name, API Key option) - remember not to share it.
2. Save the ruby `pv_names.rb` file I sent you (I cannot attach script files here).
3. Open a terminal or a console, where you have a fairly modern ruby interpreter installed.
4. Go to the folder where you have saved the ruby file.
5. Run the following:

```
ruby pv_names.rb YOUR_API_KEY
```

This should print out all PlantVariety names. Appending a redirection " > pv.txt" to the end of the line:

```
ruby pv_names.rb YOUR_API_KEY > pv.txt
```

will save the output in the 'pv.txt' file. Let me know if this does not work for you, or if you want some further explanations what's inside the code. It's fairly simple, as you see - the main complexity comes from the required pagination and the use of request headers.

**Comment by teatree1212** [comment]
file received, thank-you
