### ISSUE TITLE
Management of own, submitted data - policy

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#48]
Consider the following scenario:
 - a user starts to submit a new plant population (PP)
 - during the submission, PP is not visible to anyone but that user
 - after submission is successful, PP is visible to everyone (public data).

Should we allow to this user to delete that data any time (s)he wishes to? Or do we consider PP, once published, a part of public domain, and thus the process of publishing it - irrevocable?

Of course, the same goes for other data that users may submit to BIP.

**Comment by wjurkowski** [comment]
I'd consider it as similar to retraction of a publication. Long story short, by publishing the paper you agree to several criteria e.g. that it comes from original work; all authors agree etc. You may retract the paper but there must be a good reason for it. I'd assume similar process should take place with the data. I'll check how this is formally solved in other data repositories and how stringent it really is but it can't happen automatically.

**Comment by sarahcayling** [comment]
I think that before the data goes public the user can remove the data / terminate the submission, but once they confirm that all is ok and it goes live they would need to email us to see about getting it removed.

**Comment by Nuanda** [comment]
This is precisely how we do it now.
