### ISSUE TITLE
Change submission publishable flag name to published

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#483]
See #480 discussion. I think I insisted on a different name for submissions model, but now I see 'publishable' is not good either. Perhaps we should revert it to 'submission#published'.

**Comment by nowakowski** [comment]
Would creating an `alias_attribute` suffice? Changing the DB column name would require us to rewrite some specs - but it's your call.

**Comment by kammerer** [comment]
I don't see much sense in adding an alias. Rewriting in this case is mainly search and replace so I don't see any problem with that.
