### ISSUE TITLE
Searching for "Branched ug/g" breaks the Elasticsearch

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#493]
See the exception stack received to the email on 29th of April, around noon ;).

**Comment by kammerer** [comment]
http://stackoverflow.com/questions/31524191/is-it-possible-to-chain-fquery-filters-in-elastic-search-with-exact-matches

**Comment by Nuanda** [comment]
@kammerer Anything new here? :)

**Comment by kammerer** [comment]
IIRC I managed to prevent that error, but making it actually look for
"ug/g" is more difficult as we need to change the way text is tokenized
when building index.
20 maj 2016 17:54 "Tomasz Gubała" <notifications@github.com> napisał(a):

**Comment by Nuanda** [comment]
I only wanted the error to be avoided.

**Comment by kammerer** [comment]
It is not merged yet.
20 maj 2016 20:14 "Tomasz Gubała" <notifications@github.com> napisał(a):
