### ISSUE TITLE
Adding to About us website

### ISSUE THREAD

**Issue by teatree1212** [eSpectrum-IT/brassica#497]
Please also add my name  and email adresse to the list of contributors : Annemarie Eckes Annemarie.Eckes@tgac.ac.uk.
In the footer , please exchange the email adress " tgac.enquiries" with bip@tgac.ac.uk. these emails get forwarded to both Wiktor and me.

**Comment by Nuanda** [comment]
Couldn't find your page at TGAC - are you with Integrative Genomics Group or some other affiliation?

**Comment by teatree1212** [comment]
TGAC has changed its name and logo to [Earlham Institute](http://earlham.ac.uk/).
 Therefore, please change the footer section to
Earlham Institute ( same adress)
replace TGAC logo with EI logo
change email adresse: bip@earlham.ac.uk

can you also change the URL, but have the old one link to the new address?
bip.tgac.ac.uk/  to bip.earlham.ac.uk

**Comment by Nuanda** [comment]
I have just opened a new issue: #571 Please, move this request there. Thanks!
