### ISSUE TITLE
Management of subsequent years of plant trials

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#499]
See #488 for the beginning of this discussion (points 1. and 8.).

@teatree1212 So, my proposition, if not decided otherwise by the experimentalists, is to keep all plant trial submission annual. Therefore we will:
 - keep asking for only a single year in the 1st step of the submission
 - will ask for a single image of a plot overview, reflecting the way it was planted this exact year of the trial
 - obviously, scoring should be from this single year only
 - multi-year trials well end up with several records in the PlantTrial table, one per year.

So, the crucial question, of course, is: are there trait scoring scenarios, esp. for mean data, that average over the time axis? Like - there is a single scoring sheet that has e.g. mean values over three consecutive years? Because submission of such data might be problematic having the above assumptions.

**Comment by teatree1212** [comment]
sent out this question to experimentalists.

**Comment by teatree1212** [comment]
One experimentalists opinion sent via email. this tends to support your suggestion.

**Comment by teatree1212** [comment]
Other experimentalists opinion sent via email. i find it supports your suggestions, too. How about, we assume that such mean data can not exist for now and make people submit trials from individual years/+sites. I think even if it exists, it would be better to make the user submit the "rawer" data, including the consecutive years. This is also what the second experimentalist sais; that she would prefer more information about the individual sets of conditions.

**Hence, please go ahead and do as you suggest**. And ignore the unlikely fact that year could be used to construct an average.
In the documentation, I need to include the fact that there is no option to submit this and recommend to submit the yearly trials one by one.

**Comment by Nuanda** [comment]
@teatree1212 One more thing: do you think we should ask the user to submit that image with experiment layout as the final step (i.e. just before the "really final" annotations/comments step)? That is, after the scoring upload? Or after the PlantTrial was defined (directly after step 1)? I guess it is an arbitrary thing, to some extent, just asking your opinion.

**Comment by wjurkowski** [comment]
Perhaps the advantage of the image attachments at the very last step is increasing the chance to have it linked with correct submission to BIP and no time is waisted?

**Comment by teatree1212** [comment]
thinking in where it conceptually makes the most sense for the experimentalist to submit it is when they think about their experimental setups ( in the new step 2.5). 
But 2.5 is already getting quite a complex exercise for the users, so maybe having it before the "really final"  step (as optional), may be the best way to go.

**Comment by Nuanda** [comment]
So, the new Trial submission process would be as follows:
 1. new trial data
 - traits selection / new traits data
 - scoring template design (aka "2.5")
 - template download, filling scores in (offline), ready CSV sheet upload and parsing
 - experiment design image upload (optional)
 - final step (data ownership, comments, public/private etc.).

Is this correct?

**Comment by teatree1212** [comment]
sounds good. Correct.

**Comment by Nuanda** [comment]
@kammerer The following should be implemented:
 - extend PlantTrial model with a single file attachment, of type image (accept the usual image extensions): you may wait for @teatree1212 to name it (see below) so we have a meaningful name for that variable
 - this image attachment is optional
 - please note the data privacy management - so the image should not be publicly-available (having it behind a long hash url is probably sufficient)
 - extend the PlantTrial submission process with a new step, one before the final "comments" step (number 5. in the list above)
 - let the user upload a single image file there
 - make a PR and let me know, I'll try to extend the data table for PTs accordingly.

@teatree1212 We'll need the following texts for that from you:
 - the step 5. short label, to appear under the step number in the "tram line" graph (like "Plot overview" or sth else)
 - the short description, to appear in the grey box below (usually: the meaning of the data to be submitted here - so, more or less, what the image should show, what is it for etc.)
 - we will probably add some additional info, in a blue rectangle below, with more technical data - what file extensions we accept, what is the file size limit, etc. etc.

**Comment by teatree1212** [comment]
suggested name is "Trial layout submission" or "Trial layout"
grey box:"If available, please upload an image of the layout of your trial"

**Comment by Nuanda** [comment]
@teatree1212 Thanks. I've just thought of giving the user an explicit example - an image of the layout of a sample trial. Can you send us such an image, of a real trial, that we _can_ publish?

**Comment by Nuanda** [comment]
@kammerer Tomasz, I think things are more or less ready for you to go with this one.

**Comment by teatree1212** [comment]
![layout_example_oregin_diversity_demonstration_trial_2013-14_westbarnfield_layout_lines](https://cloud.githubusercontent.com/assets/17452217/15707498/f3920aec-27f0-11e6-97f2-d75b0c9e1004.jpg)
This sheet was already published on a different website, so I think it is possible to use this one as example.

**Comment by kammerer** [comment]
Working on it.

2016-06-01 13:08 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> Assigned #499 <https://github.com/eSpectrum-IT/brassica/issues/499> to
> @kammerer <https://github.com/kammerer>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/499#event-678260141>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAA2yUQt3x7RZBqoa5zkBJoEqbNPavm1ks5qHWg1gaJpZM4IbHnU>
> .
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
Trial layout image added to the final step, as a temporary solution.
