### ISSUE TITLE
Check for duplicates in host response trials

### ISSUE THREAD

**Issue by teatree1212** [eSpectrum-IT/brassica#503]
@nowakowski 
To me it looks like as if there are duplicated datasets in here. Could you double check things are ok please?

[link is here](https://bip.tgac.ac.uk/data_tables?fetch=host&model=trait_descriptors)

![screen shot 2016-05-13 at 12 25 59](https://cloud.githubusercontent.com/assets/17452217/15246985/fa23e098-1908-11e6-9ba1-5d2e985d2ab7.png)

**Comment by nowakowski** [comment]
Hello,

The DB appears to contain `TraitDescriptor` records which are near-exact duplicates of one other. This "phenomenon" is already present in the cs_full_web export and was carried over to our DB.

I looked at the "host response to Peronospora parasitica" trait descriptor as a representative case and what happens is that there are, in fact, four such records which differ in some fields that are not visualized in the presented screenshot. Specifically, differences exist in the `descriptor_label` field (which is likely irrelevant) and the `materials` field (which lists a different P. parasitica isolate for each `TraitDescriptor` - P005, P006, P501 and P502 respectively). All four of these descriptors contain the exact same number of attached `TraitScore` records - 409 in each case.

Perhaps visualizing the `materials` field would help resolve this issue?

**Comment by wjurkowski** [comment]
Yes, good idea - most likely the host tissues were treated with material from different isolates. It would be good to also display some other details if available (e.g. TO but changing how this is displayed is already subject of other issue)

**Comment by nowakowski** [comment]
The updated `TraitDescriptor` view includes the suggested information. Closing issue.
