### ISSUE TITLE
Rebuild TraitDescriptors browse section table

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#505]
Agreed with @wjurkowski (via an email discussion) that the current, convoluted TD table should be replaced by a more plain Traits list.

Some required fields:
  - keep the Trait scores link (might be moved to the Related dropdown)
  - add Trials link to the Related dropdown as well
  - remove all project-related columns (Species, Population, Project, Country)
  - add have more trait-related columns. Definitely both 'Units of measurement', 'Scoring method' and 'Materials' columns (see #503)
  - also, if we solve #416, perhaps 'Plant part' as well.

**Comment by teatree1212** [comment]
I think those are good elements with regard to the Old data. However, maybe not with the New to be- submitted data and the new TraitDescriptor format discussed in the email on Friday, 29 April 2016 at 16:12.

Just thinking: You will be displaying a Scoring Method-column filled with text and the Materials column that describes the materials used. This will most likely not be the way traits are submitted in the future, as we will have a "materials and methods"(Tomasz Term in the email) ( in CropOntology terms: Method description) field. 
I am referring back to the CropOntology model, and am attaching the current version of the working document here. 

I think from the old data's perspective, a materials column should be part of it to tell apart datasets like in the case of #503 . 
Again, from the new data's perspective, I think elements will change. The reason why I pledge for this is that I think that it is too tedious to fill all traitDescriptor fields in the old CropStore table. We discussed a lighter version based on CropOntology model before in emails from Friday, 29 April 2016 at 16:12.
and for new TraitDescription model display relevant here, the parts to be displayed- are trait description, plant part, method name, and scale. A .txt document should be uploaded which includes the entire method description.

Maybe we can map the current BIP "Scoring method" against new TraitDescriptors "Method description" ( CropOntology) and in the future disregard the "Materials", as they will either be part of the Method description or the .txt file.

This assumes we do in fact add the PlantPart to the TraitDescriptor level, as I feel we tend the most to in discussion #416 
[TD_template_v5.xlsx](https://github.com/eSpectrum-IT/brassica/files/268095/TD_template_v5.xlsx)

**Comment by Nuanda** [comment]
@teatree1212 Please see an alternative (perhaps: intermediate?) approach that I sent to you (and @wjurkowski and @nowakowski) today (18th of May). It is mainly in line with what you describe, just retaining old CS nomenclature, and not switching to the new CO naming model. Please respond either here or via the email, whichever you prefer. Thanks.

**Comment by teatree1212** [comment]
@Nuanda the Intermediate approach sounds good. In the future, CO id's probably need to be shown in another column. 
I did not intend to make you change the database entirely. I will just  try and put existing traits into CO and then we can attach a CO id to it. 
Ideally in the future, the user should however during trait scoring submission, when defining new traits, specify these traits in a CO format, so that we can submit these traits automatically to CO.
