### ISSUE TITLE
Setup an account for Annemarie on our server

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#509]
@teatree1212 wants to run readonly queries on the DB. See the email I sent on 20.05 for details.

**Comment by teatree1212** [comment]
Do you need help from me for this?

**Comment by nowakowski** [comment]
Hello @teatree1212,

I've configured the infrastructure in line with your request. You should be able to connect to a shell account named `annemarie` on the BIP host (`149.155.193.2`) using your private key. Once you have connected, you can access the database by typing:

`psql -d brassica`

You will be asked for a password, which I will shortly send to you via e-mail. The psql console will provide you with read-only access to all tables in the `brassica` schema, i.e. you will be able to run SELECTs, but not INSERTs, UPDATEs or DELETEs. Check [http://www.postgresql.org/docs/9.3/static/app-psql.html](url) for a more in-depth description of the console app.

Let me know if you need any further assistance.

**Comment by nowakowski** [comment]
If you're happy with this outcome, please close the issue.

**Comment by teatree1212** [comment]
thank-you. It worked.
