### ISSUE TITLE
ORCiD login problem

### ISSUE THREAD

**Issue by teatree1212** [eSpectrum-IT/brassica#511]
I was trying to login and must have put a wrong password in. But now even though I close the window I get the same error message "could not authenticate you from ORCHid Reason: "Invalid credentials"
I am using Chrome, but don't want to close the browser entirely so have only closed the tab and opened new sessions in new windows to somehow reaccess the Sign In page. However, I cannot reaccess it and the error message comes up instead.

(BTW, there is a spelling mistake in this error message : it is ORCHiD not ORCHID)

On and now- i am apparently Successfully authenticated from ORCiD account.- without having reentered my credentials or anything. I just pressed the Sign in button again and am now successfully signed in. ?

Is there any activity log I could send you for looking at what happened on my computer's side?

**Comment by Nuanda** [comment]
Annemarie, ORCiD authentication process is outside our administration zone, and to large extent, we can't control it. Some advice:
 - closing a tab in Chrome and opening a new tab might not reset your session (though it depends on the operating system and the way Chrome works in that particular environment) - usually session is per entire browser process (this is why if you open a new tab you are still signed on).
 - single sign on does that: ORCiD simply keeps your session even if BIP does not; this will go away when you close the browser windows (thus killing it's operating system process).

**Comment by teatree1212** [comment]
thanks.
