### ISSUE TITLE
Remove unused data tables from the crop store schema

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#52]
This should help us with tackling the complexity of the old data model. We should remove all tables (and references to those tables) that have no meaningful data. My simple check shown the following cases (I list table_name.primary_key_name: all distinct PK values):
 - clone_libraries.library_name: ["unspecified", "not applicable", "none"]
 - marker_sequence_hits.canonical_marker_name: ["unspecified", "not applicable", "none"]
 - row_plot_positions.row_plot_position_id: ["unspecified", "not applicable", "none"]
 - plant_line_assigned_genotypes.plant_line_name: ["unspecified", "not applicable", "none"]
 - plant_trial_collection_lists.plant_trial_collection_id: ["unspecified", "not applicable", "none"]
 - population_locus_alleles.plant_population: ["unspecified", "not applicable", "none"]
 - pop_locus_genotype_alleles.plant_population: ["unspecified", "not applicable", "none"]
 - plant_marker_fragments.scoring_unit_id: ["unspecified", "not applicable", "none"]
 - marker_variations.marker_variation: ["unspecified", "not applicable", "none"]
 - plant_individuals.plant_individual_id: ["unspecified", "not applicable", "none"]
 - clones.clone_name: ["unspecified", "not applicable", "none"]
 - plant_marker_variations.scoring_unit_id: ["unspecified", "not applicable", "none"]
 - plant_trial_collections.plant_trial_collection_id: ["unspecified", "not applicable", "none"]
 - population_genotypes.plant_population: ["unspecified", "not applicable", "none"]
 - cs_synonyms.cs_synonym_id: ["none", "unspecified"]
 - cs_images.cs_image_id: ["none", "unspecified"]
 - cs_images_lookup.cs_image_id: ["none", "unspecified"]
 - cs_additional_information.table_name: ["none", "unspecified"]
 - cs_publications.cs_publication_id: []
 - cs_people.cs_person_id: []
 - proccessed_trait_datasets.proccessed_trait_dataset_id: []
 - cs_institutions.cs_institution_id: []
 - cs_publications_lookup.cs_publication_id: []

It's a lot of unnecessary complexity and removing it should help.

@nowakowski I already work on a solution to this so tell me if you want to get involved.

**Comment by nowakowski** [comment]
@Nuanda Fully concur. I can get involved if you have a task for me, otherwise I'll continue work on ActivereRecord classes for the meaningful portion of the data model.

**Comment by Nuanda** [comment]
Do you have any proven way to find foreign keys in the current schema? I need to find all tables that reference the above tables and remove their FK columns - but I guess I might also stumble upon an ordinary column with the same name...

Only thing I though of is to check if all distinct values for that could-be-FK column are also meaningless (i.e. none, not applicable, unspecified or blank).

**Comment by wjurkowski** [comment]
We will address this issue in the survey addressed to the community.
Maybe in the first instance we could check if some of the never used keys
exist in multiple tables? If yes, we could remove copies without waiting
for feedback.

2015-03-15 16:00 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by nowakowski** [comment]
@Nuanda Can't do it automatically since there are no explicit FK indices defined in the CropStore schema. I can check manually, however.

**Comment by nowakowski** [comment]
@Nuanda @wjurkowski here you go:

  * `clone_libraries` likely not referenced anywhere
  * `marker_sequence_hits` likely not referenced anywhere
  * `row_plot_positions` referenced in `plant_individuals` with no meaningful FK values
  * `plant_line_assigned_genotypes` hard to determine - `zygote_locus_genotype` is present in multiple tables but may have nothing to do with PLAG. Need confirmation from @wjurkowski 
  * `plant_trial_collection_lists` likely not referenced anywhere and also not present in the published CropstoreDB schema
  * `population_locus_alleles` possibly referenced by `pop_locus_genotype_alleles` although that's uncertain. No meaningful FK values.
  * `pop_locus_genotype_alleles` see above. It's likely both tables can be dropped as they do not appear to be externally referenced and contain no meaningful data.
  * `plant_marker_fragments` likely not referenced anywhere
  * `marker_variations` referenced in `population_locus_alleles` and `plant_marker_fragments` but both tables are candidates for removal
  * `plant_individuals` likely not referenced anywhere
  * `clones` referenced by `probes` (there is a field called `clone_name` in `probes` which contains meaningful data).
  * `plant_marker_variations` likely not referenced anywhere
  * `plant_trial_collections` likely not referenced anywhere and also not present in the published CropstoreDB schema
  * `population_genotypes` likely not referenced anywhere   
  * `cs_synonyms` likely not referenced anywhere
  * `cs_images` referenced by `cs_images_lookup` (but see below)
  * `cs_images_lookup` likely not referenced anywhere
  * `cs_additional_information` likely not referenced anywhere
  * `cs_publications` referenced in `cs_publications_lookup` (but see below)
  * `cs_publications_lookup` likely not referenced anywhere
  * `cs_people` likely not referenced anywhere UNLESS the idea was to have `entered_by_whom` and `confirmed_by_whom` link to this table (in any case, the table contains no meaningful data)
  * `cs_institutions` referenced by `cs_people` (but see above)
  * `processed_trait_datasets` referenced by `qtl`. This FK field contains meaningful data.

**Comment by Nuanda** [comment]
@wjurkowski Wiktor, I'm not sure you got me right. I'm talking about tables that contain only three records, named 'unspecified', 'not applicable', and 'none'. Having that has no value whatsoever since these records do not convey any information. So asking the community is not needed here - we may quite safely remove that data noise.

**Comment by Nuanda** [comment]
@nowakowski Piotr, how about we remove all those tables without worrying about "references", since there is not meaningful data to be referenced there anyway, and then we simply set ALL valued of "unspecified", "not applicable" and "none" to NULL and that's it.

What do you think?

**Comment by wjurkowski** [comment]
I understand. The thing is we are not sure how the previous design was
matching community needs. Are the tables empty because there was never data
available? Or perhaps it was there but the person entering it manually
skipped it as less important? Although not used before, perhaps it be used
soon? There is certain backlog of data that was never added and there is
much more being generated as we writing.
We had this meeting on Thursday, we asked some of the questions - we will
collect answers soon.

2015-03-15 21:12 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Do I understand it correctly that what we have now is _not final_ data dump? How much more data there is and why we don't have it? Is it in the same CS data model (I really hope it is...)?

You need to understand that, based on the data we have, we are taking design decisions _all the time_. For instance - what parts to query in which way, what parts to re-normalize, what parts to drop completely. If we are not working with the real data (and, even worse, with the real data model), there could be a lot of waste...

**Comment by wjurkowski** [comment]
This is the complete dump, but there is more data to come - we were clear
about that from start. Otherwise we wouldn't develop this resource.

The first step its to clean up what we have - by no means its a time
wasted. Im 99% sure we can remove that - I just want to double check it.
Its more political than practical.

The second step is to think how to extend schema to fit e.g. more precise
phenotype description or other stuff that can come out of the new data.
We just made the first point showing the progress of the BIP. Now its time
when we will see the actual data collected from partners to understand what
is potentially not covered. Again, most likely there is nothing completely
new - but I'm always reluctant to say 100% before actually seeing things.

Maybe we can have short Skype to discuss this strategy if needed?

2015-03-16 18:09 GMT+00:00 Tomasz Gubała <notifications@github.com>:

**Comment by nowakowski** [comment]
@Nuanda Yes, I would very much welcome such a purge - it would greatly simplify our data model. I propose we do so, and then potentially consider adding tables if required by any incoming datasets which are not yet present in the CropstoreDB dump.

**Comment by Nuanda** [comment]
My thoughts exactly.

**Comment by nowakowski** [comment]
@Nuanda Nope, I dig for column names and similar values. It's a manual task, I'm afraid.
