### ISSUE TITLE
Explain 'resources' and 'attributes' in API documentation

### ISSUE THREAD

**Issue by teatree1212** [eSpectrum-IT/brassica#527]
The table/ heading "Country" is not listed in the "general introduction" part of the API documentation page. Is this indeed intended? Or does it need to be added?

**Comment by teatree1212** [comment]
I also think that in the general introduction part, you should add a sentence like:
A "resource" is the same as a table in the database schema, and an "attribute" is a column in that table. 

This wasn't clear to me when I first looked at the documentation and wasn't familiar with the underlying database components.

**Comment by Nuanda** [comment]
1. It is listed - in the 'read only models' section (slightly below). It's a read only table.
2. All right.
