### ISSUE TITLE
API_ documentation Acknowledgement

### ISSUE THREAD

**Issue by teatree1212** [eSpectrum-IT/brassica#528]
1) We have received the feedback from Graham King to  better acknowledge their prior work in the API documentation, as this part is heavily derived from their documents.
I have attached an Acknowledgement section, which can be places at the bottom of the page [https://bip.tgac.ac.uk/api_documentation](https://bip.tgac.ac.uk/api_documentation), maybe have a little  star (*) at the Headers from when the tables are mentioned ( from Country, I assume)? Or do you maybe have a better  idea? 

[API_acknowledgement_CropStore.docx](https://github.com/eSpectrum-IT/brassica/files/297666/API_acknowledgement_CropStore.docx)

2) Sorry for this second Idea in this thread but: I find that there almost needs to be a little explanatory text between the "... data" headings in the API documentation and the Tables. Maybe something like: 

Below, the resources and their attributes that can be exposed with the API are described in more detail. Use these attributes in your calls to the API. They are displayed to represent the tables similar to the schema of the database. 
( or something like that?)

**Comment by teatree1212** [comment]
I have tried to find the Acknowledgement section in the Api_documentation, but couldnt find it. Can you point me to it?

**Comment by Nuanda** [comment]
It's not deployed yet. It is already implemented, though, hence the ticket is closed. For information about what was deployed, please check my periodic reports, sent to you and to Wiktor.

I'm waiting with the deployment after we finish a large rebuilt of the trial submission process, in order to report that as well.
