### ISSUE TITLE
Redundant foreign keys in map_locus_hits

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#53]
`map_locus_hits` (MLH) includes foreign keys for a number of tables:

  - `map_positions`
  - `linkage_maps`
  - `linkage_groups`
  - `population_loci` (via `mapping_locus`)

However, only the first two of these seem necessary - the linkage group and population locus are unambiguously determined by MLH's link to `map_positions`. Can I drop the redundant FKs in MLH?

**Comment by nowakowski** [comment]
On closer analysis MLH is not actually bound to a single `map_position` because values of `map_positions.map_position` are not unique. What is the primary key of `map_positions`?

**Comment by Nuanda** [comment]
I've got another question for @nowakowski regarding that table. I find it a bit strange that the `map_position` column is a PKey (one of three, in fact). If anything, it is probably a (strange) FKey to the `map_positions` table, right? Can we remove it from the PKey array? This would be needed in order to replace its 23 cases of the 'unspecified' value to NULL.

**Comment by nowakowski** [comment]
@Nuanda It can be part of the table's PK if the intent was to have each MLH link to exactly one MP for a given pair of {linkage_group, mapping_locus} values. I would leave it be.

Btw., I think I understand the logic behind this relation now so we can close the discussion unless you have further comments/questions.

**Comment by Nuanda** [comment]
Well, I removed ALL placeholder records from ALL tables - this includes unspecified map_position values. This means, if we leave it as it is, it will relate to not existing record in the other table. If you are prepared to deal with that, it is all right to close that issue.

**Comment by nowakowski** [comment]
Okay, I understand the problem. I've run a check on `map_locus_hits` and (surprisingly!) removing `map_position` from the primary key does not violate the PK uniqueness requirement. As such, `map_position` can be dropped from the PK in this table.

**Comment by Nuanda** [comment]
Can it be also removed from the other table (map_positions)?

**Comment by nowakowski** [comment]
Yup, seems that way (I checked).

**Comment by Nuanda** [comment]
Ok, I can incorporate it still in PR #55. Should I do that?

**Comment by nowakowski** [comment]
I would recommend it.

**Comment by Nuanda** [comment]
Done - see #55

**Comment by Nuanda** [comment]
Merged. So this might be closed as far as I'm concerned.
