### ISSUE TITLE
View-side changes to new trial submission process steps 1 and 3

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#538]
The list of changes to be made so the back-end changes in #535 could be properly setup and enacted.

1. Step 01
 - remove `design_factors` property (it's auto-populated elsewhere now).
 - (related to #518) add a new `data_status` field which lets the user select between `raw data submission` (the default) and `processed data submission`; before there is a viable solution for how to describe it further, do not persist that choice in PlantTrial object in any way - for now, we will just use this value for steps 03/04

2. Step 03: the template design form, described in #502 and #488 
 - nothing below here is strictly required, provided there are some sensible defaults
 - (only for raw data) for each old/new TraitDescriptor selected/added in step02, add a simple numerical field `technical replicates number for trait <trait name here>`, with 1 as the default; should never be <1
 - make a radio group to let the user select if s/he submits scoring data for Plant lines or for Plant varieties (PL should be selected as the default)
 - (only for raw data) the design factors naming widget we have discussed in #488; please use the sample values provided by @teatree1212 there, in this exact ordering (from the biggest to the smallest factor); the result should be a 0-5 size array of `design_factor_names` starting with the biggest one. Your idea of graying out unselectable (bigger) factors in subsequent combo fields is good.

If it is more or less ready, please PR it, so I can provide (with @teatree1212 's help) nice help and hint texts there, for the user. Before then, you may see #407 for some initial suggestions by @teatree1212 as to what field names/hints could be used.

**Comment by Nuanda** [comment]
So, I would need these three properties in Step03ContentForm:
 - :technical_replicate_numbers
 - :lines_or_varieties
 - :design_factor_names

The first should be a hash keyed with trait_descriptors (remember we have both old and new TDs) and values with integers in 1+ range.

The second should be one of 'Plant lines' or 'Plant varieties' values. I prefer that to a boolean value.

The third should be an array, as described above.

**Comment by Nuanda** [comment]
I've just done required changes to step01 (step02 was cleaned up by me before) and added support for :lines_of_varieties in step03. Using the latest one in template generation.

**Comment by Nuanda** [comment]
For trait ordering, perhaps using `PlantTrialSubmissionDecorator.decorate(submission).sorted_trait_names` would be a good idea (I use it to keep the ordering of TDs consistent throughout the entire submission process, but should be also good for displaying it to the user)

**Comment by kammerer** [comment]
@Nuanda Would that be acceptable if `technical_replicate_numbers` were an array too? It turns out that passing such hash is a bit tricky.

**Comment by Nuanda** [comment]
No, but ordering is important. If it's always ordered according to

```
PlantTrialSubmissionDecorator.decorate(submission).sorted_trait_names
```

then it's probably all right. Of course requires some additional work on the generator/parser/specs side.

**Comment by teatree1212** [comment]
Can I just say here that the example list in #488 on the design factors is not in decreasing order- it was silly of me to just put something random there, I just meant it to be an example. I will make a list now.

**Comment by Nuanda** [comment]
@kammerer Please note (#543) that the number of DF might be extended beyond 5, but I guess that doesn't affect your part of the solution much.

**Comment by teatree1212** [comment]
location, room, polytunnel, greenhouse, occasion, treatment, bench, rep, area-pair, block, sub-block, row, col, plot, pot.

It would be best to just display this list in that order to the user in each of the 5 (+) selection fields and  colour out the ones used. I am not a statistician and I just asked a statistician to map the latest list on ( tank, column reservoir position) to the list above and he wasn't able to do it without the materials and methods section. So the people themselves will know. The best thing we can do is to display this list as an ordered example and make sure the instructions clearly indicate to select them from highest (design_factor_1) to lowest (design_factor_5).

**Comment by kammerer** [comment]
@Nuanda Except for specs it should be as simple as changing a single number in the code.
