### ISSUE TITLE
Data Submission_root data trial design setups

### ISSUE THREAD

**Issue by teatree1212** [eSpectrum-IT/brassica#543]
Some people want to submit real data asap. The data generated is from a root trial. 
1.
so of course the first type of data we get does NOT fit into the 99.9% of experimental trial design setups.. here, we have 7 design_factors ( I am excluding the "stunted column", which just excludes some of the  subjects as they were not fit for measurements, but maybe they also should somehow be included..)
Unfortunately, this will not fit the current submission template. 
What shall we do? Expand the number of design factors? 
I have to say, this is a very unlikely thing to happen - but maybe it is good that this happened now so we can cater for it..

**Comment by Nuanda** [comment]
We can:
 - extend the DesignFactors table with some additional design_factor_X columns, and
 - allow users to set >5 design factor names in the submission wizard.

Is this what is needed here?

**Comment by teatree1212** [comment]
I think that would be good.

**Comment by Nuanda** [comment]
@nowakowski What do you think about getting rid of these DF.design_factor_x columns and replacing them with the Postgres' array data type?

**Comment by nowakowski** [comment]
@Nuanda I rather like the idea. Should I proceed with it?

**Comment by Nuanda** [comment]
@kammerer Tomasz, there is a plan to use psql array for design factors. We will also need (just have realized that :() promote DesignFactors to a writable API. Do you know if having a writable psql array column pose any problems for API controller?

**Comment by kammerer** [comment]
@Nuanda I think so. We will need to update `Api::CreateParams` to allow passing an array of values.

**Comment by Nuanda** [comment]
I'll be looking into it first thing tomorrow - perhaps I'm able to push that quick enough to change update the current PR about new trial submission process.

**Comment by Nuanda** [comment]
10 DFs are now possible.
