### ISSUE TITLE
Crank up the max number of allowed DFs in trial submissions

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#551]
Required for #543.

**Comment by Nuanda** [comment]
@kammerer Tomasz, I have merged #553 to master, and then master to #535, so if you merge that one with your PR you should be able to go ahead with this issue. Taking into account what Annemarie wrote, putting max DF number at 10 should be sufficient for the data she got.

**Comment by kammerer** [comment]
I will do that later today.
