### ISSUE TITLE
Remove unused data columns from existing crop store schema tables

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#56]
I wrote simple check for all CS schema tables (less the ones we plan to drop anyway: #52) to see what columns have only meaningless values and, possibly, could be safely removed. Here are the results:

- Table genotype_matrices:
  * Column confirmed_by_whom has only meaningless values: ["unspecified"].
- Table marker_assays:
  * Column restriction_enzyme_a has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column restriction_enzyme_b has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column reanneal_temp has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column sequence_confirmed_by_whom has only meaningless values: ["unspecified", "not applicable", "none"].
- Table marker_sequence_assignments:
  * Column described_by_whom has only meaningless values: ["unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified"].
- Table plant_accessions:
  * Column ownership has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column pollination_method has only meaningless values: ["unspecified", "not applicable", "none"].
- Table plant_scoring_units:
  * Column seed_packet_id has only meaningless values: ["unspecified"].
- Table plant_varieties:
  * Column taxa_authority has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column subtaxa_authority has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column data_owned_by has only meaningless values: ["unspecified", "none"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "none"].
- Table plant_variety_detail:
  * Column breeder has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column agent has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column data_owned_by has only meaningless values: ["unspecified", "none"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "none"].
- Table population_loci:
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "not applicable", "none"].
- Table primers:
  * Column design_seq_id has only meaningless values: ["not applicable", "unspecified", "none"].
  * Column design_seq_source_acronym has only meaningless values: ["not applicable", "unspecified", "none"].
  * Column reanneal_temp has only meaningless values: ["not applicable", "", "none", "unspecified"].
  * Column designed_by_whom has only meaningless values: ["not applicable", "unspecified", "none"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "none"].
- Table probes:
  * Column pcr_primer_name_a has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column pcr_primer_name_b has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column forward_position has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column reverse_position has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column template_source has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column preparation_description has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column prepared_by_whom has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column probe_length has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column gene_description has only meaningless values: ["unspecified", "not applicable", "none"].
  * Column data_owned_by has only meaningless values: ["unspecified", "none"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "none"].
- Table processed_trait_datasets:
  * Column raw_dataset_id has only meaningless values: ["unspecified"].
  * Column raw_dataset_analysis_occasion has only meaningless values: ["unspecified"].
  * Column stats_analysis_description has only meaningless values: ["unspecified"].
  * Column trait_mean has only meaningless values: ["unspecified"].
  * Column trait_total_variance has only meaningless values: ["unspecified"].
  * Column additive_genetic_variance has only meaningless values: ["unspecified"].
  * Column residual_variance has only meaningless values: ["unspecified"].
  * Column average_sed has only meaningless values: ["unspecified"].
  * Column line_mean_type has only meaningless values: ["unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified"].
- Table qtl:
  * Column se_additive_effect has only meaningless values: ["unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified", "none"].
- Table qtl_jobs:
  * Column qtl_parameters has only meaningless values: ["unspecified"].
  * Column threshold_significance_level has only meaningless values: ["unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["unspecified"].
- Table scoring_occasions:
  * Column scored_by_whom has only meaningless values: ["not applicable", "none", "unspecified"].
  * Column recorded_by_whom has only meaningless values: ["not applicable", "none", "unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["none", "unspecified"].
- Table trait_grades:
  * Column described_by_whom has only meaningless values: ["not applicable", "none", "unspecified"].
  * Column data_owned_by has only meaningless values: ["none", "unspecified"].
  * Column confirmed_by_whom has only meaningless values: ["none", "unspecified"].
- Table trait_scores:
  * Column spread_type has only meaningless values: ["unspecified", "not applicable"].

@nowakowski tell me what you think.

**Comment by nowakowski** [comment]
@Nuanda Same opinion as before - drop and possibly reintroduce if required.

**Comment by Nuanda** [comment]
All right, addressed in #55 PR as well, with different rake task.

**Comment by nowakowski** [comment]
Can we close this discussion?

**Comment by Nuanda** [comment]
No. There is a PR that solves that and closes this discussion. It awaits your review and potential merge to master.
