### ISSUE TITLE
plant_scoring_units vs. plant_parts

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#57]
On the CSDB diagram `plant_scoring_units` links to `plant_parts`, however there does not seem to be a suitable FK candidate in `plant_scoring_units`. There is a field named `scored_plant_part` but its values do not match any field in `plant_parts`. @wjurkowski - could you comment?

**Comment by Nuanda** [comment]
Well, they kind of do. There are 6 unique values for scored_plant_part: 
- average of blocks                                                                                                                                                          
- average of trays                                                                                                                                                           
- pp.CanopyLeaves_01                                                                                                                                                         
- pp.EarlyLeaves_01                                                                                                                                                          
- whole plant
- whole plot

and there are three values for plant_parts.plant_part: 
- whole plot
- pp.EarlyLeaves_01
- pp.CanopyLeaves_01

So I guess we simply need to add the other three scored_plant_part values to plant_parts table, right?

**Comment by nowakowski** [comment]
Yes, this makes sense. Creating a PR to enact this fix.

**Comment by Nuanda** [comment]
@nowakowski Is this closed or not?

**Comment by nowakowski** [comment]
@Nuanda Fixed by #66, which was merged today. Closing.

**Comment by Nuanda** [comment]
ActiveRecord::UnknownAttributeError: unknown attribute 'data_status' for PlantPart.

This is due removing data_status earlier on. Please fix.

**Comment by nowakowski** [comment]
Fixed by direct commit to master. Sorry.
