### ISSUE TITLE
Make sure BIP developers get the required access to the deployment server at TGAC

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#6]

**Comment by wjurkowski** [comment]
Access granted. Please test the connection again. Is it still slow?

**Comment by Nuanda** [comment]
No, unfortunately still very slow. We will start setting up things there but please fix the network routing (or whatever makes the connection that slow). Reopening for now.

**Comment by wjurkowski** [comment]
There is general problem with LSF today, I'll let you know once its over

**Comment by kammerer** [comment]
@Nuanda @wjurkowski What is worse, I am not able to access the world from the server itself and as such I am unable to prepare deployment environment.

**Comment by wjurkowski** [comment]
Will hopefully sort it out tomorrow. To increase a chance of success. Could
you send independently ticket to computing.helpdesk@nbi.ac.uk?
Regards

2015-03-04 22:16 GMT+00:00 Tomasz Szymczyszyn <notifications@github.com>:

**Comment by wjurkowski** [comment]
I'm sure NBI will ask for details. Could you specify what types of
connections via which ports are needed?

2015-03-04 22:16 GMT+00:00 Tomasz Szymczyszyn <notifications@github.com>:

**Comment by kammerer** [comment]
Only the regular stuff needed to configure the system and run a webserver, so HTTP, DNS, SSL, SSH, etc.

Is the lack of connectivity with the outside world a deliberate security decision or is the internet access from the server unavailable due to some misconfiguration or network problem?

**Comment by wjurkowski** [comment]
We have a bit hard time with flexibility on our site. We are guinea pigs to
some extend paying the path - please be patient

2015-03-05 17:36 GMT+00:00 Tomasz Szymczyszyn <notifications@github.com>:

**Comment by Nuanda** [comment]
@kammerer Tomek, please send the official request to the people Wiktor mentioned in his mail from yesterday. By the way that might be a good time to ask for a bigger machine in case we need more memory for the full-text search indexer and some larger db joint queries.

**Comment by Nuanda** [comment]
@kammerer Wiktor told me today that all VPS-related issues should be resolved by now, so please check if the problem persists.

**Comment by kammerer** [comment]
Nope, nothing changed. I am writing that email to helpdesk.

2015-04-08 21:03 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> @kammerer <https://github.com/kammerer> Wiktor told me today that all
> VPS-related issues should be resolved by now, so please check if the
> problem persists.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/6#issuecomment-91005546>.
>



-- 
Tomasz Szymczyszyn

**Comment by Nuanda** [comment]
:(

**Comment by Nuanda** [comment]
@wjurkowski Wiktor, can you shed some light on the TGAC deployment policy? I especially mean answering the following questions:
 - will the machine, after the audit, become the production server?
 - should we install the target certificate and redirect target domain name to the current IP?
 - will we retain root access to the production machine in order to be able to perform maintenance tasks and react to issues?

**Comment by wjurkowski** [comment]
The third question definitely yes. And to make life easier we will try to
leave the VM where it is. I will give definite answers later.

2015-05-12 9:04 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Thank you.

While you are at it, please try to ask if there are any possibilities to have slightly more RAM memory on that machine. It didn't matter before Sarah requested full text search - but now some extra memory would be great.

This, of course, only makes sense if we are able to retain the current machine. Being able to work with the current setup after production deployment would, of course, be great (a lot of time saved).

**Comment by wjurkowski** [comment]
what is the desired amount you need?

**Comment by Nuanda** [comment]
I think we have 2 GB now, if I recall correctly. @kammerer Tomasz, will 1 GB more be enough?

**Comment by kammerer** [comment]
I think it should be OK.

2015-07-07 18:02 GMT+02:00 Tomasz Gubała <notifications@github.com>:

> I think we have 2 GB now, if I recall correctly. @kammerer
> <https://github.com/kammerer> Tomasz, will 1 GB more be enough?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eSpectrum-IT/brassica/issues/6#issuecomment-119249224>
> .
>



-- 
Tomasz Szymczyszyn

**Comment by wjurkowski** [comment]
I sent request 8th of July asking for 2GB more.

**Comment by Nuanda** [comment]
Should we do something extra regarding the process of obtaining a vpn account, or do we simply wait for the procedure to complete?

**Comment by Nuanda** [comment]
@wjurkowski Wiktor, great news, should we install the certificate on the server or will TGAC admins do that? In the first case - are you able to log into the machine in order to safely put the cert there?

**Comment by wjurkowski** [comment]
The certificate is already installed by Mohamed - at least the IP is
working, on the other hand there seems to be an issue with it (see
additional email)

2015-07-22 12:29 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
The domain was properly redirected and I have reconfigured nginx to serve BIP under the new name. This does, however, do not tackle the problem of certificate. It needs to be installed od the server - that is, the files should be copied to the server and the nginx web server needs to be reconfigured to recognize them.

We cannot do the later since we don't have access to the certificate/key files. I sent you instructions how to safely proceed with that.

**Comment by wjurkowski** [comment]
Could you cc Mohamed
Thanks

2015-07-25 8:52 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Done - I've just sent him an email.

**Comment by wjurkowski** [comment]
Yes, thanks!

2015-07-25 10:09 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
The memory was extended on the server - thanks. Since the administrator didn't open the SMTP server of TGAC for us, we try a different solution to be able to receive error notifications from the server.
