### ISSUE TITLE
Add automatic error reporting to admins via email

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#61]

**Comment by kammerer** [comment]
Have you considered error tracking service? Even self-hosted?
Related topic, I think using a website availability monitor could be a good thing (and may even be free http://mashable.com/2010/04/09/free-uptime-monitoring/)

**Comment by Nuanda** [comment]
We use Nagios for all our services, so don't worry about monitoring. We will set it up when we are close to done.

On the other hand we don't use Sentry or things like that. I was using Sentry when working at Cyfronet, but i found  it providing little to no extra features besides good ole' email. Perhaps if you get a LOT of traffic. But for error reporting only... We just need to make sure the outgoing server email works and that it is not blacklisted or something.

**Comment by Nuanda** [comment]
Tomasz asked TGAC admins about the outbound email traffic. Waiting for their answer.
