### ISSUE TITLE
Add server/service monitoring

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#65]

**Comment by Nuanda** [comment]
Contacted TGAC admins about that but got no response. I'd guess they have their internal monitoring services they hook up any VM they provide to.

**Comment by Nuanda** [comment]
Tomasz extended monit capabilities to test for almost everything we need. Still this depends on outbound email traffic enabling, so waiting...

**Comment by Nuanda** [comment]
Tomasz, please test if monit will also use the new mailing setup.

**Comment by kammerer** [comment]
Monit uses new smtp settings. Confirmed that it works.
