### ISSUE TITLE
We need to do something about restriction_enzymes

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#68]
In the CropstoreDB model this class links to `marker_assays` (it's actually a double relationship - via `restriction_enzyme_A` and `restriction_enzyme_B`), however these two columns had no meaningful FK values and were therefore dropped by our data curation scripts. At present, the `restriction_enzymes` table is entirely detached from the data model. We may restore the relationship with `marker_assays` but the question arises: how can existing records in that table be linked to records in `restriction_enzymes`?

Comments are welcome.

**Comment by sarahcayling** [comment]
We looked at the types of assay in the marker assay table - whilst I'm not familiar with all of them, I know that AFLP and RFLP should have at least one restriction enzyme listed, and the current data has none :( Another curation issue... These methods are not so popular any more, so maybe we won't get many records in the future, but I think we should keep the table for now, just in case, and connect it via the restriction_enzyme_A/B columns as you suggest. Not all of the assays listed will have restriction_enzymes, but some definitely should, maybe this is something we can QC upon data submission in the future?

**Comment by nowakowski** [comment]
Thanks for looking into this issue! I will restore the missing fields; however we will need your help in procuring the missing data. If there is some sort of automated algorithm which we can apply to determine which `marker_assays` should be linked to which `restriction_enzymes`? If not, we'll leave a perfunctory relationship between both tables and provide the option to link any future records to restriction enzymes.

**Comment by nowakowski** [comment]
Fixed in #135.

**Comment by Nuanda** [comment]
@nowakowski Piotr, please clarify - **none** of marker assays has either enzyme_a or enzyme_b or **some** of them do? In current BIP data no marker_assays -> enzyme relations exist - is it our curation mistake or the problem of the original CS data?

**Comment by nowakowski** [comment]
@Nuanda The problem is present in the original data - no `marker_assays` are actually assigned to any enzymes, even though two quasi-FKs are present.

**Comment by teatree1212** [comment]
For a specific map, certain marker_assays and in the cases where relevant, specific restriction enzymes should have been used. For other people to check for these markers present, they have to use the same restriction enzymes in their marker_assays. 
It is possible that the same marker_assays are used for generating different maps -with different restriction enzymes. So the link between marker_assays and restriction enzymes is not that standard.

It may be possible to curate the existing data by looking at the papers that published these maps. If it is possible to point out the marker_assays used in publications (?), I could try and curate it. 
As @sarahcayling  mentioned, the popularity of those methods is decreasing, so it may not be my first curation priority.
