### ISSUE TITLE
About us (and terms of use?) page content

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#75]
Maybe it's a good time to deal with the About us page - before we dive again in more serious business of data model. Please provide us with the intended content. Of course, it is entirely up to you what we put there, but I imagine things like the following:
 - about BIP itself
 - about TGAC and how TGAC help Brassica breeders community
 - terms of use
 - your personal info (pictures, direct contact emails), if you want to.

If terms of use will grow to a large document, we may put it into a separate page. I understand you'd want something like "How to cite us" there - and perhaps something more about data ownership, publication rights etc. Perhaps some disclaimers.

**Comment by nowakowski** [comment]
@Nuanda Perhaps this request could be folded into #23 ?

**Comment by Nuanda** [comment]
No, this is another view of the system.

**Comment by Nuanda** [comment]
I added some information there so it does not look temporary when deployed as public. In case you'd like to add some more information there, just tell me and send the text.
