### ISSUE TITLE
Do we need the `version` table?

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#76]
The table seems to have tracked old changes in the CropstoreDB model. It doesn't seem to affect, or be in any way related to, the cropstore data model. I would suggest dropping it.

Alternatively we may retain the table and insert a record which reflects our current development work. If you prefer this option please tell us what the meaning of `08p` and `d5.10.4` in the `version` column is.

**Comment by wjurkowski** [comment]
I think, we should keep track of db versions somehow. In the future we will
have new version whenever new data arrive.

Again, as in other issues, not sure if we need separate table for this.
Does it have to be encoded in the actual db? Could this info go somewhere
else? What is the SOP in keeping track of data base content?

Regards


2015-03-27 10:25 GMT+00:00 Piotr Nowakowski <notifications@github.com>:

**Comment by nowakowski** [comment]
Allow me to explain. :) Ruby on Rails (which is what we're using to develop BIP) introduces the concept of *migrations* which represent transformations of the database model. In simple terms, we begin with a source model (let's call it *M*) and apply migrations iteratively to obtain the target model:

M -(run migration m1)-> M' -(run migration m2)-> M'' (and so on in that fashion).

Our source model is the existing (old) CropStoreDB schema, i.e. schema version **cs_08p_0.4.1_d5.10.4**. Each migration is stored in the project tree as a separate file (look for them in the `db/migrate` directory). The purpose of migration files is to aggregate DDL (Data Definition Language) commands - e.g. adding/removing fields, altering field attributes, creating/dropping tables etc. Rails extenst the model with a separate table (`schema_migrations`) which keeps track of which migrations have been applied.

If you believe that further extensions of the data model will be frequent then perhaps it makes sense to retain the `version` table, if only to find out who bears responsibility for a given change. If you concur then I would only ask for a suggested version name for our new CropstoreDB model - since I'm unsure as to the relevant semantics (e.g. "08p" and "d5.10.4").

**Comment by wjurkowski** [comment]
Thanks for the info!
OK, we were thinking about two separate things. You schema, me the content.
:)

Schema: I'll leave only the newly introduced (schema_migrations). We don't
care about keeping the identifier of old schema version. As soon as we
reach the consensus of new data model the schema is not going to change
later. And in the meantime we are the only site responsible for it -
therefore we can scrap version table.

Content: I'm keen on tracking status of the stored project-related content.
We are going to have separate "builds" after a major project output is
added. How can we keep versioning of it?







2015-03-27 11:08 GMT+00:00 Piotr Nowakowski <notifications@github.com>:

**Comment by nowakowski** [comment]
@wjurkowski Yes, that's exactly it. Sorry for the confusion. :) Regarding your other question - could you specify what exactly constitutes "project output"? If it's a new set of plant populations then there are several ways to identify such "builds" - for instance by querying the `date_added` field in the `plant_populations` table - or perhaps by differentiating projects by the value of the `data_provenance` field therein. It is also possible to create a separate table (e.g. `projects`) and have it aggregate plant populations.

If by "project output" you meant something else then let me know and I'll suggest an alternative approach.

**Comment by wjurkowski** [comment]
This is the right meaning. Maybe data_provenance is better than using date
as the submission could be done step-wise.

2015-03-27 11:59 GMT+00:00 Piotr Nowakowski <notifications@github.com>:

**Comment by sarahcayling** [comment]
Hi, Wiktor and I had a discussion and we would like to propose the following:

When data is uploaded it gets a date/timestamp and then when users cite the database they can say that they accessed it on that date, and people can recreate that database by filtering the records by that date.
It would also be good to report the DB schema versions and dates at which they went live on a page somewhere, so that people can also relate back to which version they accessed at a future date if needs be. 
The legacy versioning from cropstore is not something which we care about preserving, as those numbers mean nothing to us either :)

**Comment by nowakowski** [comment]
@sarahcayling Can do. We can attach timestamp columns to each table and automatically populate them whenever records are inserted. Regarding schema versions - each record in the `schema_migrations` table represents a new version and the first eight characters of the field actually correspond to its creation date (e.g. `20150331...` stands for 31 March 2015) so the information you're looking for is retrievable.

I will drop the old `version` table.

**Comment by Nuanda** [comment]
We could add the DB schema versions history at the bottom of the "About us" page, where (as I imagine) some "How to cite BIP" info will be given as well, right?

**Comment by wjurkowski** [comment]
Yes, it's on the way...

2015-03-31 21:32 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by wjurkowski** [comment]
For BIP citation we could have at the moment:
Ayling S., Jurkowski W., Smith j., Kowalski A., Brassica Community, Brassica Information Portal, version: 1234

**Comment by Nuanda** [comment]
@wjurkowski Wiktor, this issue is about the versions table. For the issue regarding the About Us page content - see #75 .

@nowakowski - what is the current status of this "versions" issues? Do you know what to do or do you require further input?

**Comment by nowakowski** [comment]
@Nuanda The table will be dropped. I'm going through tickets in chronological order and haven't yet reached this one but you can treat this table as nonexistent.

**Comment by Nuanda** [comment]
I just wanted to know whether it's ok to reassign this issue to you.

**Comment by nowakowski** [comment]
It is indeed.
