### ISSUE TITLE
Can we drop 'probes.pcr_yes_or_no'?

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#79]
All CropstoreDB records show 'N' in this field, and we have already dropped `pcr_primer_name_a` and `pcr_primer_name_b` due to lack of useful data.

**Comment by wjurkowski** [comment]
yes

2015-03-27 13:44 GMT+00:00 Piotr Nowakowski <notifications@github.com>:

**Comment by nowakowski** [comment]
Fixed in #82
